### ISSUE TITLE
Debug模式断点不起作用，提示Resolved locations: 0

### ISSUE THREAD

**Issue by GuangDai** [xmake-io/xmake-vscode#101]
### Xmake 版本

v2.6.5+master.7a8ccde

### 操作系统版本和架构

ArchLinux 5.17.5-arch1-1

### 描述问题

VSC的默认调试和cmake的调试功能都可以正常进入断点，但xmake无法进入断点 提示为Resolved locations: 0 
xmake插件除了设置debug config type，其他没有设置过，安装什么样子，现在就什么样子。
尝试过重装、恢复默认设置且使用cppgdb等，都无法进入断点
没找到类似的issue，谷歌的相关问题说codelldb的问题，但其他调试方式（都用的lldb）都没问题

![image](https://user-images.githubusercontent.com/59678726/166412663-44116e02-e4f8-443a-b430-4e95da3ce0fe.png)

### 期待的结果

能进入断点，逐步调试

**Comment by waruqi** [comment]
切到 debug 模式，并且确保有配置 `add_rules("mode.debug")`

**Comment by GuangDai** [comment]
> 切到 debug 模式，并且确保有配置 `add_rules("mode.debug")`

已切换，有配置 add_rules("mode.debug")

**Comment by waruqi** [comment]
你点的哪个调试按钮？

**Comment by GuangDai** [comment]
> 你点的哪个调试按钮？

F5或者status bar里面的debug按钮

vsc这个默认debug工作正常
![image](https://user-images.githubusercontent.com/59678726/166414051-04029dcc-a27c-4f30-80c7-45bb85e0395f.png)

**Comment by waruqi** [comment]
不要点这个，跟这里没关系，点底下 toolbar 里面的调试按钮，readme有说明

**Comment by GuangDai** [comment]
> 不要点这个，跟这里没关系，点底下 toolbar 里面的调试按钮，readme有说明

是的，我提到的不是这个按钮，有问题的是这个
![image](https://user-images.githubusercontent.com/59678726/166417244-750a057b-1546-4f4a-8304-82a846fc2617.png)
和 F5  
![image](https://user-images.githubusercontent.com/59678726/166417277-6d98d406-33ec-4070-83fc-5ce6a367e6ac.png)

执行xmake 的debug就是这个样子
![image](https://user-images.githubusercontent.com/59678726/166417326-3d2af35d-235f-4f68-b131-a3834cbfa6b9.png)
可以看到断点没有进入就执行了cout和void函数

**Comment by GuangDai** [comment]
尝试降级到1.6.1后该Bug就没了，再升级到1.6.2 也没Bug了
Hmmmmm，有点不明白到底哪出问题了
