### ISSUE TITLE
more modes support

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake-vscode#103]
### 你在什么场景下需要该功能？

目前插件中只能设置debug和release，即使xmake.lua中添加了其他mode（releasedbg，etc）也无法识别并设置

### 描述可能的解决方案

从xmake.lua中读取可设置的mode，而非固定只有两种mode

**Comment by waruqi** [comment]
这两天没空搞，可以来个 pr ，或者等后面有空 我再看下

**Comment by waruqi** [comment]
可以了
