### ISSUE TITLE
xmake-vscode doesn't configure any more after "XMake: CleanAll" action

### ISSUE THREAD

**Issue by v1nh1shungry** [xmake-io/xmake-vscode#105]
### Xmake 版本

2.6.5

### 操作系统版本和架构

5.10.16.3-microsoft-standard-WSL2

### 描述问题

在执行`XMake: CleanAll`命令后，再执行`XMake: Configure`命令将无反应。

### 期待的结果

在执行`XMake: CleanAll`命令后，再执行`XMake: Configure`后将配置项目，输出配置文件。

### 工程配置

任一工程配置都能触发这个问题，以下是最小可复现例子：
```lua
add_rules("mode.debug", "mode.release")

target("tutor")
    set_kind("binary")
    add_files("src/*.cpp")
```

### 附加信息和错误日志

我认为是因为在
https://github.com/xmake-io/xmake-vscode/blob/1b70af63d1d608898e71057b25ea8f5ca274dfea/src/xmake.ts#L614-L633
中没有将`this._optionChanged`重新设置为`true`，而项目配置也没有变化，导致`onConfigure`函数不执行。
https://github.com/xmake-io/xmake-vscode/blob/1b70af63d1d608898e71057b25ea8f5ca274dfea/src/xmake.ts#L459-L460

**Comment by waruqi** [comment]
来个 pr 改下？

**Comment by v1nh1shungry** [comment]
Okay~
