### ISSUE TITLE
Error when executing XMake: CreateProject in an empty directory

### ISSUE THREAD

**Issue by v1nh1shungry** [xmake-io/xmake-vscode#106]
### Xmake 版本

2.6.5

### 操作系统版本和架构

5.10.16.3-microsoft-standard-WSL2

### 描述问题

在一个空文件夹中（理所当然地，xmake-vscode插件并未启动，因为目录下还没有xmake.lua文件），执行`XMake: CreateProject`命令会出现错误：
![image](https://user-images.githubusercontent.com/98312435/167590902-a2fdb554-cfa7-41d4-b112-a35a64528fab.png)

### 期待的结果

正常进入项目配置选择环节。我认为这是合理的，隔壁的CMake插件也支持这样高楼平地起的操作。

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
不是有蓝色按钮提示么，点下呢

**Comment by v1nh1shungry** [comment]
我知道，也许是我吹毛求疵吧，但是我觉得在Create Project这个动作下报错没有xmake.lua文件果然有点匪夷所思和annoying，这个说是bug不足为过吧。感谢耐心地回复！

**Comment by waruqi** [comment]
凑活着能用就行了，我暂时没时间处理插件问题，也可以提个 pr 过来
