### ISSUE TITLE
Sometimes the extension not work in VSCode.

### ISSUE THREAD

**Issue by LynnTong** [xmake-io/xmake-vscode#109]
### Xmake 版本

xmake v2.6.5+202204301432, A cross-platform build utility based on Lua

### 操作系统版本和架构

Linux 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### 描述问题

出问题的版本：**vscode 扩展版本 1.6.3。**
在我的电脑上（win10及linux）均有xmake扩展激活不了的情况：
1. 具体表现为：打开含 xmake.lua 文件的工程目录，vscode 底栏中无 xmake 相关功能。
2.  查看扩展安装页的运行时状态，显示：Cannot read properties of undefined (reading 'sort')
![截图 2022-05-11 22-00-08](https://user-images.githubusercontent.com/22219956/167870293-ac2baa07-a0f5-49ee-8687-8690226b3319.png)
3. 若使用xmake在Cli中新建工程，之后使用vscode打开工程目录，扩展又是工作正常的。
4. 扩展回退到版本 1.4.9，一切正常。

### 期待的结果

不知道这是否为我个人环境的问题？
作者大佬有空的话，可以确认下该问题是否存在。

**Comment by LynnTong** [comment]
[cpputest_multiplatform-main.zip](https://github.com/xmake-io/xmake-vscode/files/8671204/cpputest_multiplatform-main.zip)
**工程已上传**

**Comment by waruqi** [comment]
应该可以了，再试试，是因为你这 target 没加 add_files，解析 files 异常了

**Comment by LynnTong** [comment]
十分感谢！现在可以正常工作了
