### ISSUE TITLE
xmake 插件在VS Code中无法正常使用

### ISSUE THREAD

**Issue by QELD** [xmake-io/xmake-vscode#110]
### Xmake Version

1.6.4

### Operating System Version and Architecture

Windows10 破解版 （组装机器商家装的）

### Describe Bug

新建一个文件夹后用VsCode打开，然后用命令面板使用xmak：newfiles,没反应

### Expected Behavior

按照B站作者的视频做的 但是效果不一样

**Comment by WadeGao** [comment]
> 先命令行 xmake create test 创建一个工程，打开看下。

还是无法启动xmake插件
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/49817941/182788604-f2dfd0a3-2de5-495c-85c8-87074fda760c.png">

**Comment by waruqi** [comment]
那就不知道了，可以自己拉取插件代码调下

**Comment by duterhappy** [comment]
在debian平台使用Remote-ssh开发的时候遇到了同样的问题，xmak：newfiles,没反应

**Comment by duterhappy** [comment]
遇到了同样的位置，然后把vscode版本降低到1.64.2就解决了，应该是vscode更新导致xmake插件和vscode版本不兼容的问题

**Comment by chengjunjian** [comment]
确实不兼容 1.7.x 版本

**Comment by waruqi** [comment]
我这里 Version: 1.70.2 正常加载

**Comment by chengjunjian** [comment]
w

> 我这里 Version: 1.70.2 正常加载

我是在remote Linux 模式下使用的

**Comment by waruqi** [comment]
没试过，你可以拉插件源码调下。

**Comment by WadeGao** [comment]
这个问题，我昨天在macOS上又遇到了。单纯reload Windows并不好使，你需要彻底退出vscode再重新打开，就一切如常了。

**Comment by xystar2012** [comment]
![image](https://github.com/xmake-io/xmake-vscode/assets/17939797/40cddd9c-453f-4bf0-92ea-014c4248b429)
vscode ssh-remote 远程调试代码时，不识别 xmake 调试器，底部也没有工具栏，好像无法调试。
这里 的 配置说明 https://github.com/xmake-io/xmake-vscode 对 ssh-remote 好像不适用。 @waruqi

**Comment by waruqi** [comment]
xmake cli , cpptools 什么的装了么

**Comment by xystar2012** [comment]
xmake cli 命令行都有，应该装了， cpptools 也装了

**Comment by xystar2012** [comment]
今天再次打开 vscode 打开 remote-ssh 远程目录 好像恢复了，thanks.

**Comment by shikai-123** [comment]
我重启下了设备和vscode，就行了
