### ISSUE TITLE
点击调试按钮，无黄色高亮提示，不识别断点

### ISSUE THREAD

**Issue by xiaomi2077** [xmake-io/xmake-vscode#115]
### Xmake 版本

xmake v2.6.7+master.91395ec

### 操作系统版本和架构

Linux nx-desktop 4.9.140-tegra #1 SMP PREEMPT Fri Apr 16 01:50:20 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux

### 描述问题

![image](https://user-images.githubusercontent.com/33375652/174469318-63c37416-394f-4f4d-8866-3e2d12acf785.png)
测试代码，第14行打断点。
点下方小虫子调试，等很长时间也不会在main入口出现黄色高亮提示，并且点的断点变成灰色。点击`继续`会直接运行结束，点击`单步跳过`或`单步调试`会跳转到libc-start.c，如下图
![image](https://user-images.githubusercontent.com/33375652/174469425-304553c7-4fd7-497c-aa39-8f930e4e7205.png)

已重装xmake-vscode插件，重启过电脑，重启过vscode

### 期待的结果

正常调试

**Comment by waruqi** [comment]
之前你不是还可以的么 https://github.com/xmake-io/xmake-vscode/issues/114

确认下是否 debug 编译，是否配置了 add_rules("mode.debug")

**Comment by xiaomi2077** [comment]
![image](https://user-images.githubusercontent.com/33375652/174470228-f1585065-73ad-4675-8ca4-0988486359ee.png)
对，之前可以。我加了add_rules("mode.debug")。

**Comment by waruqi** [comment]
如果之前可以，那么现在应该也可以，可以自己看下做过什么改动

还不行就自己拉下 xmake-vscode 源码自己调下，也可能是 vscode 本身的问题 也可以到 vscode 那边去反馈下

**Comment by xiaomi2077** [comment]
我在./vscode/setting.json中加了`xmake.additionalConfigArguments=-enable-pretty-printing`，想调试查看stl里的值。发现无效后，又把这个配置删除了。是这里的问题吗

**Comment by waruqi** [comment]
> 我在./vscode/setting.json中加了`xmake.additionalConfigArguments=-enable-pretty-printing`，想调试查看stl里的值。发现无效后，又把这个配置删除了。是这里的问题吗

这是传给 xmake f 的，你有定义这个option？而且我看格式也不对，目前仅支持  xmake f --key=val , xmake f -k

**Comment by xiaomi2077** [comment]
> xmake.additionalConfigArguments=-enable-pretty-printing

这个只是示意，写下setting.json中的是符合格式的。

我先重装vscode和xmake试试吧，不想再折腾了

**Comment by xiaomi2077** [comment]
重新新建项目就好了，估计哪里配置出问题了。
