### ISSUE TITLE
在Windows下自动选择调试器

### ISSUE THREAD

**Issue by 2283572185** [xmake-io/xmake-vscode#127]
### 你在什么场景下需要该功能？

我正在编写一个库，需要使用调试器。然而在Windows下，xmake插件发起的调试会话总是使用那个支持codeview格式调试信息的调试器，即使我选择的是gcc工具链。而gcc使用的dwarf格式的调试信息不能被codeview调试器解析，使得不能调试gcc编译的软件。这只针对微软的c/c++提供的调试器。

### 描述可能的解决方案

应该允许用户自行选择调试器使用的调试信息格式，因为通过平台或者工具链去判断并不准确。因为像clang，既能产生dwarf，又能产生codeview，因此应该让用户去选择。

### 描述你认为的候选方案

在底部状态栏中添加一个调试器模式选择框。

### 其他信息

如果说能根据工具链给出的信息和编译选项来自动推断出调试器类型就更好了。例如，gcc工具链就一定可以用dwarf的调试器去调试，而遇上clang就可以通过clang -v去分析它的默认target，或者分析编译参数，如--target，-gdwarf，-gcodeview去推断调试信息格式。比如说--target=x86_64-pc-windows-gnu就是dwarf，--target=x86_64-pc-windows-msvc就是codeview，这样就能自动选择了。

**Comment by waruqi** [comment]
自己插件配置里切下

https://github.com/xmake-io/xmake-vscode/issues/19

**Comment by 2283572185** [comment]
好的，如果有一天会做自动推导就更好了👍
