### ISSUE TITLE
工程创建与头文件支持

### ISSUE THREAD

**Issue by wangzhankun** [xmake-io/xmake-vscode#13]
### 你在什么场景下需要该功能？
我自己本身有一个工程，目录树如下：
![image](https://user-images.githubusercontent.com/35724924/66249995-c0e28400-e76e-11e9-91ac-4d6bb7c49b22.png)
这里我是使用cmake进行自动化编译的。当我尝试使用xmake进行工程创建的时候，发现只能在src目录下进行创建，就变成了下面这样：
![image](https://user-images.githubusercontent.com/35724924/66250010-f6876d00-e76e-11e9-8477-3bc1e93be49b.png)
事实上，我希望我的工程应当与src在同级目录。这里产生的问题就有一是我本身就是一个git仓库，但是xmake又帮我创建了一个git仓库，二是我的所有东西都与源文件放在了一起。事实上我希望能够自己定义目录结构。同时进行编译过程中，发现include失败，如下：
![image](https://user-images.githubusercontent.com/35724924/66250068-fcca1900-e76f-11e9-924a-e80c30eee566.png)

### 描述可能的解决方案

或许可以允许用户指定新的目录，并创建目录树如下：
![image](https://user-images.githubusercontent.com/35724924/66250060-c9878a00-e76f-11e9-88d5-69eb3b4b33df.png)
同时不要自己创建git仓库。让用户保有更大自主权。另一方面，关于头文件目录希望作者能够解决一下。

**Comment by waruqi** [comment]
目前基于源码自动扫描生成的xmake.lua，只作为快速上手的辅助功能，用于快速生成一个基本的xmake.lua文件，但并不保证完全可靠，毕竟每个用户的项目源码结构千奇百怪，目前的扫描生成还没那么智能。。

用户通过xmake生成完xmake.lua，还是需要自己稍微做些人为的修改才可使用，除非是非常简单的项目。。

具体可以看下文章：https://tboox.org/cn/2017/01/07/build-without-makefile/

用户可以通过CreateProject命令，或者xmake create 命令，创建各种类型项目的空工程，然后自己往里面添加源文件。。

xmake-vscode的插件目前只提供了构建、调试、运行所需的基本功能，但是对于IDE相关功能很多都是没有提供的，比如添加源文件，还是需要自行维护xmake.lua
