### ISSUE TITLE
没有正确处理项目路径

### ISSUE THREAD

**Issue by UUUnmei** [xmake-io/xmake-vscode#135]
### Xmake 版本

2.6.9

### 操作系统版本和架构

win10 专业版 21h2

### 描述问题

所在目录D:\C++ code\playxmake 
执行插件提供的命令 xmake: CreateProject -> c++ -> console

执行输出如下
![image](https://user-images.githubusercontent.com/54660562/186645529-aed682fa-4f44-4910-85f2-8012502bd25d.png)
![image](https://user-images.githubusercontent.com/54660562/186649352-42d9a6ce-db63-4f45-a47f-81a46127fb84.png)

项目创建在了d:\C++ 文件夹（还是额外创建的），项目名code\playxmake，  

应该创建在当前的目录吧

### 期待的结果

首先确实是我的这个目录命名不太合适，
不过如果能考虑一下就最好了
给生成的命令中的路径加个引号之类的
谢谢

**Comment by waruqi** [comment]
这个问题 我修了
