### ISSUE TITLE
Cannot debug when using liburing

### ISSUE THREAD

**Issue by fonqL** [xmake-io/xmake-vscode#139]
### Xmake 版本

2.7.1

### 操作系统版本和架构

Ubuntu 22.04 on Win10 WSL

### 描述问题

xmake.lua
```lua
add_rules("mode.debug", "mode.release")
set_languages("c++17")
set_toolchains("clang")
set_warnings("all")

add_requires("liburing")
add_packages("liburing")

target("demo")
  set_kind("binary")
  add_files("src/main.cpp")
```

main.cpp
```c++
#include <iostream>
int main() {
    std::cout << "1234\n";
}
```

可以运行，可以命令行调试（xmake run -d），但是不能在vscode里调试（即点击状态栏调试按钮或按F5）
```bash
.../demo/build/linux/x86_64/debug/demo: error while loading shared libraries: liburing.so.2: cannot open shared object file: No such file or directory
```
相关：
```bash
$ ls ~/.xmake/packages/l/liburing/2.1/2e6104ac1acb47ddb318f33dd2d128ee/lib
liburing.a  liburing.so  liburing.so.2  liburing.so.2.1.0  pkgconfig
```

settings.json
```json
"xmake.customDebugConfig": {
        "type": "lldb",
        "request": "launch",
        "name": "Debug",
    }
```

### 期待的结果

可以调试

**Comment by waruqi** [comment]
这个你要自己调下插件了，看看 runenvs 里面是否少了部分变量

https://github.com/xmake-io/xmake-vscode/blob/master/assets/target_runenvs.lua

```console
xmake l assets/target_runenvs.lua targetname
```

https://github.com/xmake-io/xmake-vscode/blob/master/src/xmake.ts#L829-L843

**Comment by fonqL** [comment]
`xmake l assets/target_runenvs.lua demo`
输出
```
[]
__end__
```
<https://github.com/xmake-io/xmake-vscode/blob/3751e4a627bc05d845e5507e3646ec9cbc0fb6e8/assets/target_runenvs.lua#L48>
这一行返回两个空map。。所以envs还是空集后面就到`print("[]")`了

<https://github.com/xmake-io/xmake/blob/1496036a67cf746df72b7140096e08b6913a3d9d/xmake/modules/private/action/run/make_runenvs.lua#L67>
`target:get("runenvs")` 和之后的`target:get("runenvs")`都返回空。。

在target_runenvs.lua打印了一下target ( `print(target)` )
[target.txt](https://github.com/xmake-io/xmake-vscode/files/9670657/target.txt)
target:get似乎只在第3669行的_INFO = {...}执行查找，比如target:get("packages"), target:get("warnings")是有结果的

**Comment by waruqi** [comment]
会从这里找

https://github.com/xmake-io/xmake/blob/1496036a67cf746df72b7140096e08b6913a3d9d/xmake/modules/private/action/run/make_runenvs.lua#L46-L50

既然 xmake run 可以跑，对比下两边的差异

**Comment by fonqL** [comment]
<https://github.com/xmake-io/xmake/blob/1496036a67cf746df72b7140096e08b6913a3d9d/xmake/modules/private/action/run/make_runenvs.lua#L85>
？但是我是linux平台啊

**Comment by waruqi** [comment]
linux 看这里 https://github.com/xmake-io/xmake/blob/1496036a67cf746df72b7140096e08b6913a3d9d/xmake/actions/run/main.lua#L121

**Comment by fonqL** [comment]
怎么给xmake debug。。本地没找到main.lua，是二进制分发吗（用apt+ppa装的）

**Comment by waruqi** [comment]
xmake l os.programdir 看下本地安装目录，有所有 lua 脚本

**Comment by fonqL** [comment]
<https://github.com/xmake-io/xmake/blob/1496036a67cf746df72b7140096e08b6913a3d9d/xmake/actions/run/main.lua#L120-L156>
在main.lua中，执行流程是：先get环境变量，再加入LD_LIBRARY_PATH，**再执行代码**，最后恢复旧的环境变量

而在target_runenvs.lua中，执行流程是：先get环境变量，再加入LD_LIBRARY_PATH，然后就恢复旧的环境变量，最后开启调试运行代码，没有环境变量LD_LIBRARY_PATH

**Comment by waruqi** [comment]
> 
https://github.com/xmake-io/xmake/blob/1496036a67cf746df72b7140096e08b6913a3d9d/xmake/actions/run/main.lua#L120-L156
在main.lua中，执行流程是：先get环境变量，再加入LD_LIBRARY_PATH，再执行代码，最后恢复旧的环境变量

而在target_runenvs.lua中，执行流程是：先get环境变量，再加入LD_LIBRARY_PATH，然后就恢复旧的环境变量，最后开启调试运行代码，没有环境变量LD_LIBRARY_PATH

跟恢复没关系，那个脚本只是为了 print envs 结果出来，恢复前，envs 已经取出来了

https://github.com/xmake-io/xmake-vscode/blob/d9cfd83236ac434ebdea105bd65d3e1d4c09c6c0/assets/target_runenvs.lua#L63

之后调试，会把envs 直接透传给 debugger，跟当前环境是否有 LD_LIBRARY_PATH 没任何关系。

**Comment by waruqi** [comment]
run 那个我改进了下，具体看 https://github.com/xmake-io/xmake-vscode/discussions/142#discussioncomment-3760924

**Comment by fonqL** [comment]
> 跟恢复没关系，那个脚本只是为了 print envs 结果出来，恢复前，envs 已经取出来了

但就是没取出来啊
见我上面的评论
<https://github.com/xmake-io/xmake-vscode/issues/139#issuecomment-1261706610>

**Comment by waruqi** [comment]
没取出来也跟恢复envs没啥关系，是其他问题导致，得继续跟进去

> 如果是空的，也跟这个恢复没啥问题，应该是其他问题

**Comment by fonqL** [comment]
那问题出在哪呢，是make_runenvs还是target的生成呢
<https://github.com/xmake-io/xmake-vscode/blob/a592193f985d6b3e5296755e9d6f2ce77c16e3f8/assets/target_runenvs.lua#L31>

**Comment by waruqi** [comment]
大概知道原因了 这里面没把 envs 设置进去

https://github.com/xmake-io/xmake-vscode/blob/a592193f985d6b3e5296755e9d6f2ce77c16e3f8/assets/target_runenvs.lua#L47

**Comment by waruqi** [comment]
改了下，再试试

**Comment by fonqL** [comment]
。。原来问题是codelldb插件的“type”: "lldb"调试配置根本不接受environment属性。。在launch.json中写出来检查发现报黄了。。按左侧调试栏的按钮果然也显示找不到共享库路径。。
![image](https://user-images.githubusercontent.com/75968297/193072948-ad929762-eacd-4457-811c-47e71d33e215.png)
我知道的一个解法是改成
```json
"env": {
    "LD_LIBRARY_PATH": "/home/fofo/.xmake/packages/l/liburing/2.1/2e6104ac1acb47ddb318f33dd2d128ee/lib",
},
```
可能是个breaking change，不知道有没有其他指定共享库路径的方法

另外一个work around就是改成用"type": "cppdbg"调试

**Comment by waruqi** [comment]
cppdbg 和 codelldb 的 env 配置格式不同？

**Comment by fonqL** [comment]
![image](https://user-images.githubusercontent.com/75968297/193074226-13bc3ae6-e284-4fa7-8a3a-c62da02e8a53.png)
![image](https://user-images.githubusercontent.com/75968297/193074602-b20aa0f1-0fa4-4c4c-b48a-1df3f3b57557.png)
而且改了后type: lldb确实可以成功调试

**Comment by waruqi** [comment]
这里又说 `env {}` 反而不行

https://stackoverflow.com/questions/29971572/how-do-i-add-environment-variables-to-launch-json-in-vscode

这个有官方文档么，envs 配置不是应该统一的么，为啥 lldb 和 cpptools 的 key 和格式还不同？

**Comment by fonqL** [comment]
![image](https://user-images.githubusercontent.com/75968297/193076072-0a165b29-4b4c-49c9-b71a-11293240abba.png)
。。我觉得vscode的调试就是以type为依据分发给相应的调试插件处理的吧，不同插件处理的属性就不一样

**Comment by waruqi** [comment]
今天没空搞了，你可以直接提个 pr 过来帮忙搞下。

这里转下 targetRunEnvs 传入 env 就行了。
https://github.com/xmake-io/xmake-vscode/blob/c3195efcdba08a48ac5deefac7df32393ce117c5/src/debugger.ts#L82-L93

**Comment by waruqi** [comment]
改进过了 再试下
