### ISSUE TITLE
build按钮失灵

### ISSUE THREAD

**Issue by wangzhankun** [xmake-io/xmake-vscode#14]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
build按钮有时可以使用，有时不可以使用。主要表现就是在我修改cpp文件之后，按build按钮没有任何反应，必须自己手动输入xmake命令进行编译。除了build按钮不可用之外，运行按钮也不可用，只有debug按钮可以使用。重启vscode之后都可以使用。原因未知。
平台如下：
ubuntu 18.04
vscode 1.38.1 x64
VMware 15pro

**Comment by waruqi** [comment]
我这边暂时没法复现这个问题，不太好查  等之后如果有复现此类问题 我再查下

**Comment by wangzhankun** [comment]
你或许可以创建一个大些的工程。然后使用一下。建议在虚拟机下复现。也很有可能需要等一段时间。我这边的情况就是过了一会儿就会出现这个问题。然后重启之后又可以用了。
![image](https://user-images.githubusercontent.com/35724924/66256389-e9469e80-e7bf-11e9-978e-ce1cc3b467ab.png)

**Comment by waruqi** [comment]
这边暂时没有大工程来复现这个问题。

**Comment by 1m188** [comment]
我也遇到过类似的问题，主要是每次打开vscode之后插件会自动打开一个终端，这个时候build和run等按钮还是好用的，但是一旦关闭了这个终端之后上述两个按钮就没有用了，哪怕重新打开一个终端也没有用，只有debug按钮还是好的。除非重启vscode，这时又重新打开终端之后，build和run按钮又好用了。
Windows_NT x64 10.0.18362
vscode版本: 1.39.2 (system setup)

**Comment by waruqi** [comment]
build 和 run 是在插件起的那个终端下 发送对应命令来执行构建的

 如果这个终端被用户强行关闭了  但是插件里面还维护着那个终端的无效引用  发送命令过去就没效果了

我只能看看是否能够监听到终端被销毁的事件  然后下次build重新起个新的终端操作  如果不行的话 就没办法了

**Comment by waruqi** [comment]
@wangzhankun @1m188 这块我改进过了，用tasks重写执行命令的逻辑，这些问题应该都解决了，而且效果和体验也比之前好了不少。

另外如果要处理编译错误解析，同时更新下xmake到dev版本：xmake update dev 之前的版本有点小问题，解析编译错误会有问题。
