### ISSUE TITLE
Set Default Target命令显示错位

### ISSUE THREAD

**Issue by QuanBomian** [xmake-io/xmake-vscode#15]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题

使用xmake命令Set Default Target时Target显示有错位问题，功能可以正常使用

### 期待的结果

显示没有错位

### 错误信息

无

### 相关环境

VSCode1.39.1
Windows 10 1903
xmake v2.2.8+201908261511

### 其他信息

![image](https://user-images.githubusercontent.com/39216613/66714958-0f87c200-edf0-11e9-9370-f25178ec3e0a.png)

![image](https://user-images.githubusercontent.com/39216613/66714962-1dd5de00-edf0-11e9-98fe-117c65e350b0.png)

**Comment by waruqi** [comment]
目前暂时没有win/vscode环境，等后两天有环境了给你看下

**Comment by waruqi** [comment]
你更新下vscode插件，应该可以了，如果还是不行，请更新xmake到dev版本，xmake update dev

**Comment by QuanBomian** [comment]
问题已解决
