### ISSUE TITLE
关于工具链的选择功能

### ISSUE THREAD

**Issue by 1m188** [xmake-io/xmake-vscode#16]
当前的版本中只有选择目标平台target的选项，类似Windows，Linux，macos之类。但是我在Windows下做开发的话电脑上面不仅装了vs 2017的工具链，还装了clang和gcc，如果直接使用插件提供的选项进行编译的话会默认使用vs 2017，而如果要想使用其他的工具链就只能够自己写脚本或者配置task实现。
希望能够加入一个类似vscode插件cmake-tools的工具链的选择功能，能够扫描机器上面的工具链并且列出来以供选择，这样就方便许多。

**Comment by waruqi** [comment]
目前可以在 xmake.additionalConfigArguments 里面配置各种环境 比如设置 --vs=2017

这个相当于 xmake config xxxxx 后面的附加配置参数  可以配置各种环境
