### ISSUE TITLE
set_group bug in vscode

### ISSUE THREAD

**Issue by Extra-Creativity** [xmake-io/xmake-vscode#163]
### Xmake Version

2.7.5

### Operating System Version and Architecture

Win10 22H2, x86_64

### Describe Bug

The minimal project that causes this bug has been uploaded to [my temporary repository](https://github.com/Extra-Creativity/TestCode).

In this project, `set_group` [here](https://github.com/Extra-Creativity/TestCode/blob/0fdf0e3374fa044be1fe32dae5e4e68585d8a77e/xmake.lua#L16) will cause incorrect subgroups in vscode.

### Expected Behavior

VSCode will make `Test2` a subgroup of `Test`.

**Comment by A2va** [comment]
This is normal [`set_group`](https://xmake.io/#/manual/project_target?id=targetset_group) work only with **Visual Studio** not Visual Studio Code

**Comment by Extra-Creativity** [comment]
Err..Okay, I mistake it as a feature for VSCode because of [this discussion](https://github.com/xmake-io/xmake/discussions/3294#discussioncomment-4689336), where the maintainer thinks so.

So if not, could you please consider it as a to-do item? Currently, `set_group` will cause dump when generating Visual Studio project, as I mentioned in [xmake issue](https://github.com/xmake-io/xmake/issues/3303), so it seems impossible to see whether it works on VS. But hopefully this feature can be extended to more IDEs or platforms :-).

**Comment by waruqi** [comment]
> set_group will cause dump when generating Visual Studio project

@see https://github.com/xmake-io/xmake/issues/3303#issuecomment-1385494248

> So if not, could you please consider it as a to-do item? 

vscode support group, https://github.com/xmake-io/xmake-vscode/blob/8e0842ceb2056d270fb25e894590df4f735da46f/src/explorer.ts#L16

But it was contributed by others and I'm not sure about the implementation yet, maybe it's not stable. You can also debug the plugin source code yourself.

**Comment by Extra-Creativity** [comment]
I've updated the repository; now it should make `Test2` a subgroup of `Test`, and library `Test3` will be in `Test2`; But it will only work like what you show, that is, `Test3` is in the group `Test` rather than its subgroup.

**Comment by A2va** [comment]
I have fixed it !
![image](https://user-images.githubusercontent.com/49582555/213434824-bd44fa56-1270-408c-85ac-c77a60de7b43.png)

**Comment by Extra-Creativity** [comment]
Appreciate your quick fix! Thank you!
