### ISSUE TITLE
c++无法调试,无法执行.权限不够

### ISSUE THREAD

**Issue by gooker** [xmake-io/xmake-vscode#168]
### Xmake 版本

2.7.6

### 操作系统版本和架构

centos7.8

### 描述问题

之前vmware安装centos7.8虚拟机没遇到这个问题, 刚换成virtualbox 虚拟机同样的centos7.8的镜像 大部分情况下无法调试c++.
手动都gdb都无问题

&"warning: GDB: Failed to set controlling terminal: \344\270\215\345\205\201\350\256\270\347\232\204\346\223\215\344\275\234\n"
/bin/bash: /.../build/linux/x86_64/debug/xxx: 权限不够
/bin/bash: 第 0 行:exec: /.../build/linux/x86_64/debug/xxx: 无法执行: 权限不够
[root@localhost rcs]# 

### 期待的结果

点击调试按钮, 有几率可以调试,大部分情况可以调试

**Comment by waruqi** [comment]
你拉下插件源码，加载调试下，看下送入调试器的程序路径是否 ok

**Comment by gooker** [comment]
> 你拉下插件源码，加载调试下，看下送入调试器的程序路径是否 ok

有源码调试的教程吗

**Comment by waruqi** [comment]
直接 vscode 打开插件源码目录，点运行就可以调了。

或者找下网上的文档，也可以看下 https://tboox.org/cn/2017/10/11/xmake-vscode/

**Comment by gooker** [comment]
没有vscode的调试环境,经过重新调整virtualbox的网卡(原来是 nat模式+端口转发,改成双网口,一个网卡与主机通信nat+一个网卡host模式上网) 目前调试都正常了

**Comment by gooker** [comment]
还是会遇到,之前没有解决

**Comment by gooker** [comment]
gg半天无解 应该是virtualbox 共享目录vboxfs的问题,和插件无关系
