### ISSUE TITLE
compile_commands 的生成无法触发

### ISSUE THREAD

**Issue by zheng95z** [xmake-io/xmake-vscode#169]
### Xmake 版本

2.6.4

### 操作系统版本和架构

Windows 10

### 描述问题

请问现在使用插件时如何触发 `compile_commands.json` 的生成？我之前使用时，使用 `xmake:build` 可以触发，现在无论如何尝试都没有办法自动使其生成。

### 期待的结果

生成 `compile_commands.json`。

**Comment by zheng95z** [comment]
在别的 issue 里找到了，是要更新 `xmake.lua` 时会触发其生成。感谢作者。

**Comment by star-hengxing** [comment]
也可以打开打开 vscode 的命令面板用 xmake.UpdateIntellisense
