### ISSUE TITLE
VS code IntelliSense 问题

### ISSUE THREAD

**Issue by 316064780** [xmake-io/xmake-vscode#18]
> Note: If it is a 'bug report' or 'feature request', please select the corresponding issue template, otherwise this issue will be not replied. 

### Describe the problem details
Please describe your problem details here.

在VS code 中 C++ 源文件 如下
bool cPlcManager::ReadMtrCtrl(    中的 ` ::`  会被标记为 红色波浪线 

请问在 c_cpp_properties.json 文件中应该怎么配置，貌似 IntelliSense 的分析识别并不是很有效果

**Comment by waruqi** [comment]
这。。这个似乎跟xmake没啥关系吧，c_cpp_properties.json 的配置问题，你应该找找c++那个插件的IntelliSense配置使用。

目前xmake.lua里面add_includedirs的设置还不支持跟 IntelliSense 做自动匹配。如果是这块的问题，后续如果有时间 我会考虑加上支持。。

**Comment by 316064780** [comment]
是没有关系，这不没有其他的渠道可以询问的，只能这里求助了

**Comment by waruqi** [comment]
这块我也不是很清楚哦，之前也没研究过 vscode/IntelliSense

**Comment by waruqi** [comment]
现在支持了，可以参考这个说明配置启用下，https://github.com/xmake-io/xmake-vscode/issues/40#issuecomment-657171811
