### ISSUE TITLE
环境变量设置XMAKE_ROOT=y不生效

### ISSUE THREAD

**Issue by dwpeng** [xmake-io/xmake-vscode#182]
### Xmake 版本

v2.7.7+20230315

### 操作系统版本和架构

WSL

### 描述问题

安装最新版插件`v2.0.4`后，在环境变量设置了`XMAKE_ROOT=y`以后，插件一直报错`xmake not found.`，原因可能是xmake无法读取环境变量中的`XMAKE_ROOT`，之前是可以运行的。

### 期待的结果

希望xmake-vscode插件可以在配置时，在现有的`Xmake: Executable`参数的基础上，可以提供额外的以ROOT模式运行的配置。

**Comment by waruqi** [comment]
root 下不推荐使用，也不做相关支持，请在非 root 下使用。。插件上不会去做相关的设置的，你可以自己全局设置环境变量
