### ISSUE TITLE
Startup experience is rough, not thought through

### ISSUE THREAD

**Issue by lewisl** [xmake-io/xmake-vscode#193]
### Is your feature request related to a problem? Please describe.

You MUST start from an empty folder to use CreateProject.

I'd say this is overly restrictive and not necessary.

1. Let's say you instead start by creating a cpp file.  
2. Then, you want to make it an xmake project. This notion that you MUST start with a project is typical c-ish rigamarole boilerplate.  It's very simple to copy the template xmake.lua file into the current folder and to make an .xmake folder.

Why is this so hard?  Nothing bad can happen.  Instead, I have to make a new directory; make it a project; copy my existing files to the this directory?  For what--to reinforce some misguided sense of c-ish manliness?  Because of ancient traditions that must not be violated?

Programming should be about functioning code, not about rigid traditions that have no technical foundation.

xmake is leading towards a new view of building and simplicity. So, break free!

### Describe the solution you'd like

I just said it.  While a current folder is open, create a project if no previous xmake.lua file is found.  So easy.

**Comment by waruqi** [comment]
CreateProject generates not only xmake.lua but also `src/main.cpp` and many other project files.

If the directory is not empty, this will overwrite the files and existing code in the user directory. This should not be the result the user wants.

**Comment by lewisl** [comment]
You don’t have to over-write files.  Create files with distinct names.  That’s not really hard.

From: ruki ***@***.***>
Reply-To: xmake-io/xmake-vscode ***@***.***>
Date: Friday, May 5, 2023 at 6:46 PM
To: xmake-io/xmake-vscode ***@***.***>
Cc: Lewis Levin ***@***.***>, Author ***@***.***>
Subject: Re: [xmake-io/xmake-vscode] Startup experience is rough, not thought through (Issue #193)


CreateProject generates not only xmake.lua but also src/main.cpp and many other project files.

If the directory is not empty, this will overwrite the files and existing code in the user directory. This should not be the result the user wants.
