### ISSUE TITLE
root用户下提示未安装xmake

### ISSUE THREAD

**Issue by ChrisCatCP** [xmake-io/xmake-vscode#195]
### Xmake 版本

v2.7.8+20230406

### 操作系统版本和架构

ubuntu

### 描述问题

在使用vscode 远程本机wsl的ubuntu使用xmake插件时   因为用户是root  会导致xmake命令运行失败 插件会提示找不到xmake

### 期待的结果

对root用户运行插件的情况没有处理 能处理一下正确提示我去切换用户就好了

**Comment by waruqi** [comment]
提示 dev 版本改进过了。。请切到非 root 用户运行
