### ISSUE TITLE
关于运行功能的改进意见

### ISSUE THREAD

**Issue by codehz** [xmake-io/xmake-vscode#22]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题

目前的运行功能是主动打开一个终端，然后发送输入事件到终端，这里存在很多问题
1 是如果当前终端刚好有内容，则发送过去的输入就会直接尾随到其后，问题很大
2 是（大概是为了避免其他问题导致）发送两个换行符，这样会使得运行后的程序也收到两个换行。。。影响了执行结果
3 是如果vscode打开项目后再创建xmake相关文件，终端就不会自动打开了，然后快捷操作也不能使用了

### 期待的结果

使用 VSCode 内建的Task机制执行构建和运行命令，具体来说使用类似这个插件的机制去运行：https://marketplace.visualstudio.com/items?itemName=spmeesseman.vscode-taskexplorer

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by waruqi** [comment]
恩，这块我回头改进下

**Comment by waruqi** [comment]
这个我改进过了，你更新到v1.2.7试试，不过2.2.9的xmake有点小bug，导致xmake-vscode里面处理编译错误输出会有问题，你可以同时更新到 dev版本xmake，就能正常处理编译错误信息了。。
