### ISSUE TITLE
修改build目录后无法debug

### ISSUE THREAD

**Issue by gooker** [xmake-io/xmake-vscode#220]
### Xmake 版本

2.8.2

### 操作系统版本和架构

centos7.8

### 描述问题

xmake设置里面,修改build目录到/tmp/build(原来好像是$(projectdir)/build).编译正常,文件都在指定文件夹下面.但是调试提示 "The target program not found!"

### 期待的结果

可以正常debug

### 工程配置

gcc version 10.2.1 20210130 (Red Hat 10.2.1-11) (GCC) 环境,未修改build目录一切正常

### 附加信息和错误日志

无法查看

**Comment by gooker** [comment]
调试插件打印program not found的目录发现,这个debug调用的文件路径 是$(projectdir)+自定义目录+linux/x86_64/...
不过不会改lua或者配置

**Comment by waruqi** [comment]
我修了，一会更新下插件

**Comment by gooker** [comment]
> 

更新测试没问题了
