### ISSUE TITLE
v2.2.2版插件会导致xmake的CPU占用超高

### ISSUE THREAD

**Issue by pankey888** [xmake-io/xmake-vscode#221]
### Xmake 版本

2.2.2

### 操作系统版本和架构

Linux Mint 21 Cinnamon

### 描述问题

近期更新v2.2.2插件后，频繁出现xmake占用的CPU非常高：
![MJ_BN4Z0F2QDE4AQU_U 0S8](https://github.com/xmake-io/xmake-vscode/assets/52560244/c6ab7330-3d03-4069-a20d-65fe984bee6e)
关闭语法检查后，仍会出现：
![Q_0~HX8QXC O0BES37G(_YC](https://github.com/xmake-io/xmake-vscode/assets/52560244/919f8f14-987b-4185-88a8-c8532b20ecf5)
xmake版本从v2.7.8升级到v2.8.2都是一样的现象，怀疑问题出在插件上。

### 期待的结果

减少CPU的占用。

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
你手动执行这个命令，自己调下
