### ISSUE TITLE
调试运行找不到qt相关环境变量

### ISSUE THREAD

**Issue by Wzshun** [xmake-io/xmake-vscode#225]
### Xmake 版本

2.8.2

### 操作系统版本和架构

windows10

### 描述问题

点击vscode的状态栏的调试，发现qt相关的程序无法调试。运行是可以的。

这对于codelldb和cpptools都是一样的情况。

然后在`.vscode/settings.json`中单独设置调试的配置（关于qt路径的），即可成功调试。如下：
```
"xmake.customDebugConfig": {
        "env": {
            "PATH": "I:/DevelopmentTools/QT/Qt5.9.9/5.9.9/msvc2017_64/bin;${env:PATH}"
        },
        "environment": [
            {
                "name": "PATH",
                "value": "I:/DevelopmentTools/QT/Qt5.9.9/5.9.9/msvc2017_64/bin"
            }
        ],
        "stopAtEntry": false,
}
```

### 期待的结果

不用设置qt相关路径，即可调试。

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
更新下插件，然后在更新下 xmake 后试试，应该可以了。。`xmake update -s dev`
