### ISSUE TITLE
状态栏点击build，会触发xmake config，导致原配置丢失

### ISSUE THREAD

**Issue by Wzshun** [xmake-io/xmake-vscode#230]
### Xmake 版本

2.8.3

### 操作系统版本和架构

windows10

### 描述问题

在使用xmake的option相关特性时，往往自己配置了一个option（如强关联与本地路径），option的默认值是项目通用的。

而在开发过程中，先行配置好本地的option，随后点击状态栏的build，xmake会触发config（假如改了构建模式，比如说从debug改成release），这样触发config后，会导致刚才已经配置好的option丢失（恢复到了option的default值）。

### 期待的结果

希望本机配置的option不会被，xmake f冲刷掉成默认值。

看过之前关于增量式config的讨论，知道实现它的一个复杂性或者不可行。

但我这里想要可能类似于一个 project.user 相关的一个配置文件，保存着本机开发所配置的option，然后xmake f 恢复到默认值后，再加上这么个类似的文件选项到，到最终配置项xmake.conf里。。

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
xmake f --import/--export 可以导入导出的

**Comment by Wzshun** [comment]
通过在.vscode的settings.json里，添加
```
"xmake.additionalConfigArguments": [
        "--toolchain=msvc",
        "--vs=2017",
]
```
诸如类似的配置，xmake vscode 的build按钮触发的config，会追加这些配置。

暂时这个方法，可以达到类似项目的xmake本机配置。

**Comment by yangbigtree** [comment]
> 通过在.vscode的settings.json里，添加
> 
> ```
> "xmake.additionalConfigArguments": [
>         "--toolchain=msvc",
>         "--vs=2017",
> ]
> ```
> 
> 诸如类似的配置，xmake vscode 的build按钮触发的config，会追加这些配置。
> 
> 暂时这个方法，可以达到类似项目的xmake本机配置。

请问下你是在哪里看到这个配置的呢？我想了解一下vscode的xmake插件在settings.json中还有提供哪些参数
