### ISSUE TITLE
希望作者考虑增加一个侧边栏用于操作

### ISSUE THREAD

**Issue by tiansin** [xmake-io/xmake-vscode#24]
### 描述可能的解决方案
类似于这个扩展:
https://marketplace.visualstudio.com/items?itemName=ms-vscode.cmake-tools

可以把一些功能放在侧边栏上操作,目前是全部放在状态栏.

在我电脑上Live Share插件的状态栏不知道为什么夹在xmake栏目的中间,看起来怪怪的.
![Screen Shot 2020-03-03 at 10 56 18](https://user-images.githubusercontent.com/4232281/75738713-f00d1980-5d3d-11ea-9ea6-1ef620a5c1e9.png)

**Comment by waruqi** [comment]
我记得之前就是参考这个插件做的，先这么凑活着用吧，等回头有时间我再看看。

**Comment by waruqi** [comment]
人家提了个 pr 支持了，https://github.com/xmake-io/xmake-vscode/issues/91
