### ISSUE TITLE
工程脚本域调用 print 会导致无法调试

### ISSUE THREAD

**Issue by HaroldCC** [xmake-io/xmake-vscode#240]
### Xmake 版本

2.8.5

### 操作系统版本和架构

Windows10 19045.3803

### 描述问题

xmake项目脚本域如果添加print的时候，调试会带出来print的内容，导致json解析失败，无法进行调试
![image](https://github.com/xmake-io/xmake-vscode/assets/49848762/b99e1d28-c400-4d3e-ba37-036cdb6381f3)

### 期待的结果

print不影响调试

### 工程配置

add_rules("mode.debug", "mode.release")

target("test")
    set_kind("binary")
    add_files("src/*.cpp")

    on_config(function (target) 
        print("test")
    end)

### 附加信息和错误日志

![image](https://github.com/xmake-io/xmake-vscode/assets/49848762/4f84234f-17f6-4311-ad72-8c8aaa18b351)

**Comment by HaroldCC** [comment]
https://github.com/xmake-io/xmake-vscode/blob/758c9a54088c5d92cb6d3046252981638cf4dc8c/src/xmake.ts#L1059

我尝试使用try包裹这条语句处理解析错误，但是不知道是不是正确的处理方式：
`
            if (targetRunEnvs) {
                try {
                    targetRunEnvs = JSON.parse(targetRunEnvs);
                } catch (error) {
                    targetRunEnvs = null;
                }
            } else {
                targetRunEnvs = null;
            }
`

**Comment by waruqi** [comment]
这种没办法，你只能删了调试 print

你这样处理只能规避部分，没法根本上解决问题，targetRunEnvs 还是会 null 了，很多时候，一些依赖的 dll 就没法加载起来，照样调试不了，尤其是 win 下

**Comment by HaroldCC** [comment]
那工程脚本域想输出一些信息，能否调用其他的打印输出，规避这个问题？

**Comment by waruqi** [comment]
没有，有输出就会捕获，要么你不要在 on_config 里调，放 before_build 里调。。。要么用 lua 的断点调试直接调，不走 print 


要么 print 了，直接终端 xmake cli 编译，看调试输出，还要啥 vscode
