### ISSUE TITLE
设置xmake build目录后调整不回去默认的

### ISSUE THREAD

**Issue by gooker** [xmake-io/xmake-vscode#244]
### Xmake 版本

2.8.5

### 操作系统版本和架构

centos7.8

### 描述问题

1. centos7 c++设置编译到/tmp/build下面,结果多个项目编译出来有莫名其妙的问题(崩溃)
2. 通过vscode里面配置改回原来出现 实际编译还是在/tmp/build下面
<img width="800" alt="1703406062012" src="https://github.com/xmake-io/xmake-vscode/assets/5688076/9dd7ddc7-c62f-4e58-a76c-d5f1858cb93b">
3. 然后不论在vscode里面还是在命令行xmake 编译都出现直接结束,检测不到文件变化等
<img width="295" alt="1703406246381" src="https://github.com/xmake-io/xmake-vscode/assets/5688076/c8e21412-798b-4ad6-a17f-97939b3fea05">

### 期待的结果

正常切换编译目录 

### 工程配置

正常c++的

### 附加信息和错误日志

未加参数

**Comment by waruqi** [comment]
xmake f -c
xmake -rv

**Comment by gooker** [comment]
> xmake f -c xmake -rv

可以了
