### ISSUE TITLE
vscode 调试配置launch.json无法添加visualizerFile属性

### ISSUE THREAD

**Issue by HiiroAyane** [xmake-io/xmake-vscode#246]
### Is your feature request related to a problem? Please describe.

在调试过程中无法可视化变量值

### Describe the solution you'd like

launch.json xmake支持添加可视化文件，使变量值可见

**Comment by HiiroAyane** [comment]
> xmake.customDebugConfig 可自定义任何配置

请问具体在哪里设置呢？

**Comment by waruqi** [comment]
设置 -> xmake -> customDebugConfig

**Comment by waruqi** [comment]
你可以搜下  issues 。有相关配置

**Comment by HiiroAyane** [comment]
在settins.json 里面添加以下内容：
"xmake.customDebugConfig": {
		"visualizerFile": "D:/xxx.natvis"
}
