### ISSUE TITLE
C++设置xmake build目录重启虚拟机后编译可能检测不到代码变化

### ISSUE THREAD

**Issue by gooker** [xmake-io/xmake-vscode#248]
### Xmake 版本

2.8.6

### 操作系统版本和架构

centos7.8

### 描述问题

遇到好多次,之前实在没办法就取消了.最近想把单项目调整一下编译目录,一开始还正常,好像重启或者切换别的虚拟机就不行了.
删了build目录可以重新全编,但是编完之后修改代码就不会再编了
![image](https://github.com/xmake-io/xmake-vscode/assets/5688076/2590edef-6cb6-4e19-abf5-12bf3b3a1c5e)

### 期待的结果

可以编译

### 工程配置

正常

### 附加信息和错误日志

如图

**Comment by gooker** [comment]
执行了 xmake f -c 后 ,workspace里面设置build目录 再也不生效了... 重设还是在当前目录build下

**Comment by gooker** [comment]
另外 我看xmake.lua里面可以设置build相关的,但是只能是 set_targetdir /set_objectdir/set_dependir 三个,还有.gen还在build下面,

**Comment by gooker** [comment]
我发现 设置build目录 会出现各种问题,单独设置 set_targetdir 出现不linking
![image](https://github.com/xmake-io/xmake-vscode/assets/5688076/4501531e-8f8f-43ef-a84b-678dbf41ceb0)

**Comment by waruqi** [comment]
我这里可以

改完目录，需要重新执行 XMake: configure 配置生效。

```console
 *  正在执行任务: xmake -v 

checking for Xcode directory ... /Applications/Xcode.app
checking for Codesign Identity of Xcode ... Apple Development: waruqi@gmail.com (T3NA4MRVPU)
checking for SDK version of Xcode for macosx (x86_64) ... 14.0
checking for Minimal target version of Xcode for macosx (x86_64) ... 14.0
checking for zig ... no
checking for zig ... no
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang ... ok
checking for the c++ compiler (cxx) ... clang
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang ... ok
checking for flags (-fPIC) ... ok
checking for flags (-fvisibility-inlines-hidden) ... ok
checking for flags (-O3) ... ok
checking for flags (-DNDEBUG) ... ok
[ 25%]: cache compiling.release src/main.cpp
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -c -Qunused-arguments -target x86_64-apple-macos14.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG -o build/.objs/test/macosx/x86_64/release/src/main.cpp.o src/main.cpp
checking for flags (-MMD -MF) ... ok
checking for flags (-fdiagnostics-color=always) ... ok
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ ... ok
checking for the linker (ld) ... clang++
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ ... ok
checking for flags (-fPIC) ... ok
[ 50%]: linking.release test
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o build/macosx/x86_64/release/test build/.objs/test/macosx/x86_64/release/src/main.cpp.o -target x86_64-apple-macos14.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -stdlib=libc++ -lz -Wl,-x -Wl,-dead_strip
[100%]: build ok, spent 2.462s
 *  终端将被任务重用，按任意键关闭。 

 *  正在执行任务: xmake -v 

[100%]: build ok, spent 0.023s
 *  终端将被任务重用，按任意键关闭。 

 *  正在执行任务: xmake f -p macosx -a x86_64 -m release -o /private/tmp/test3/build2 -c 

checking for Xcode directory ... /Applications/Xcode.app
checking for Codesign Identity of Xcode ... Apple Development: waruqi@gmail.com (T3NA4MRVPU)
checking for SDK version of Xcode for macosx (x86_64) ... 14.0
checking for Minimal target version of Xcode for macosx (x86_64) ... 14.0
 *  终端将被任务重用，按任意键关闭。 

 *  正在执行任务: xmake -v 

checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang ... ok
checking for the c++ compiler (cxx) ... clang
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang ... ok
checking for flags (-fPIC) ... ok
checking for flags (-fvisibility-inlines-hidden) ... ok
checking for flags (-O3) ... ok
checking for flags (-DNDEBUG) ... ok
[ 25%]: cache compiling.release src/main.cpp
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -c -Qunused-arguments -target x86_64-apple-macos14.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG -o build2/.objs/test/macosx/x86_64/release/src/main.cpp.o src/main.cpp
checking for flags (-MMD -MF) ... ok
checking for flags (-fdiagnostics-color=always) ... ok
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ ... ok
checking for the linker (ld) ... clang++
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ ... ok
checking for flags (-fPIC) ... ok
[ 50%]: linking.release test
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o build2/macosx/x86_64/release/test build2/.objs/test/macosx/x86_64/release/src/main.cpp.o -target x86_64-apple-macos14.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -stdlib=libc++ -lz -Wl,-x -Wl,-dead_strip
[100%]: build ok, spent 1.409s
 *  终端将被任务重用，按任意键关闭。 
 * ```

**Comment by waruqi** [comment]
> 另外 我看xmake.lua里面可以设置build相关的,但是只能是 set_targetdir /set_objectdir/set_dependir 三个,还有.gen还在build下面,

正常，这些都是细粒度 api，全局改 buildir 得用 `set_config("buildir", path.join(os.projectdir(), "other_build"))`

**Comment by gooker** [comment]
> 我这里可以
> 
> 改完目录，需要重新执行 XMake: configure 配置生效。
> 
> ```
>  *  正在执行任务: xmake -v 
> 
> checking for Xcode directory ... /Applications/Xcode.app
> checking for Codesign Identity of Xcode ... Apple Development: waruqi@gmail.com (T3NA4MRVPU)
> checking for SDK version of Xcode for macosx (x86_64) ... 14.0
> checking for Minimal target version of Xcode for macosx (x86_64) ... 14.0
> checking for zig ... no
> checking for zig ... no
> checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang ... ok
> checking for the c++ compiler (cxx) ... clang
> checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang ... ok
> checking for flags (-fPIC) ... ok
> checking for flags (-fvisibility-inlines-hidden) ... ok
> checking for flags (-O3) ... ok
> checking for flags (-DNDEBUG) ... ok
> [ 25%]: cache compiling.release src/main.cpp
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -c -Qunused-arguments -target x86_64-apple-macos14.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG -o build/.objs/test/macosx/x86_64/release/src/main.cpp.o src/main.cpp
> checking for flags (-MMD -MF) ... ok
> checking for flags (-fdiagnostics-color=always) ... ok
> checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ ... ok
> checking for the linker (ld) ... clang++
> checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ ... ok
> checking for flags (-fPIC) ... ok
> [ 50%]: linking.release test
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o build/macosx/x86_64/release/test build/.objs/test/macosx/x86_64/release/src/main.cpp.o -target x86_64-apple-macos14.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -stdlib=libc++ -lz -Wl,-x -Wl,-dead_strip
> [100%]: build ok, spent 2.462s
>  *  终端将被任务重用，按任意键关闭。 
> 
>  *  正在执行任务: xmake -v 
> 
> [100%]: build ok, spent 0.023s
>  *  终端将被任务重用，按任意键关闭。 
> 
>  *  正在执行任务: xmake f -p macosx -a x86_64 -m release -o /private/tmp/test3/build2 -c 
> 
> checking for Xcode directory ... /Applications/Xcode.app
> checking for Codesign Identity of Xcode ... Apple Development: waruqi@gmail.com (T3NA4MRVPU)
> checking for SDK version of Xcode for macosx (x86_64) ... 14.0
> checking for Minimal target version of Xcode for macosx (x86_64) ... 14.0
>  *  终端将被任务重用，按任意键关闭。 
> 
>  *  正在执行任务: xmake -v 
> 
> checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang ... ok
> checking for the c++ compiler (cxx) ... clang
> checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang ... ok
> checking for flags (-fPIC) ... ok
> checking for flags (-fvisibility-inlines-hidden) ... ok
> checking for flags (-O3) ... ok
> checking for flags (-DNDEBUG) ... ok
> [ 25%]: cache compiling.release src/main.cpp
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -c -Qunused-arguments -target x86_64-apple-macos14.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG -o build2/.objs/test/macosx/x86_64/release/src/main.cpp.o src/main.cpp
> checking for flags (-MMD -MF) ... ok
> checking for flags (-fdiagnostics-color=always) ... ok
> checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ ... ok
> checking for the linker (ld) ... clang++
> checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ ... ok
> checking for flags (-fPIC) ... ok
> [ 50%]: linking.release test
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o build2/macosx/x86_64/release/test build2/.objs/test/macosx/x86_64/release/src/main.cpp.o -target x86_64-apple-macos14.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -stdlib=libc++ -lz -Wl,-x -Wl,-dead_strip
> [100%]: build ok, spent 1.409s
>  *  终端将被任务重用，按任意键关闭。 
>  * ```
> ```

请问一下 buildir在vscode里面配置 或者xmake 存在linux系统的什么位置 都是存在当前代码的目录下吗. 我查一下是不是配置信息重启后改了等等

**Comment by waruqi** [comment]
vscode 的配置，你可以  google 下  vscode 存哪了

**Comment by gooker** [comment]
修改目录后 xmake f -c ,然后删除目录重编
