### ISSUE TITLE
使用 Remote - SSH 远程开发无法编译

### ISSUE THREAD

**Issue by tiansin** [xmake-io/xmake-vscode#25]
### 描述问题
主机: MacOS 10.15.3
服务端: Windows 2019, OpenSSH-Server

![Screen Shot 2020-03-17 at 01 55 35](https://user-images.githubusercontent.com/4232281/76786614-77549580-67f2-11ea-9bb6-b90b0a2a1cdc.png)

测试代码为xmake创建的基础工程,没有添加其它代码,点底部的 build 报告错误.
```
> Executing task: xmake -v <

/d : The term '/d' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ /d /c xmake -v
+ ~~
    + CategoryInfo          : ObjectNotFound: (/d:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
我试了下正常在命令行输入xmake则能正常编译.

![Screen Shot 2020-03-17 at 02 00 49](https://user-images.githubusercontent.com/4232281/76786988-26916c80-67f3-11ea-9df3-917d815994c8.png)

**Comment by waruqi** [comment]
等回头有时间我看下

**Comment by tiansin** [comment]
@waruqi 研究了一下应该是vscode task自身的问题,把 terminal.integrated.shell.windows 换成cmd就可以了,估计是powershell不支持附加 /d /c 参数.

**Comment by waruqi** [comment]
哦哦
