### ISSUE TITLE
支持配置调试选项

### ISSUE THREAD

**Issue by pbdm** [xmake-io/xmake-vscode#26]
### 你在什么场景下需要该功能？

调试第三方库的时候需要在 launch.json 里配置 source map

### 描述可能的解决方案

添加对应扩展配置选项, 例如 code-lldb 的: https://github.com/vadimcn/vscode-lldb/blob/v1.5.0/MANUAL.md#source-path-remapping

**Comment by waruqi** [comment]
收到，回头我改进下

**Comment by waruqi** [comment]
相关问题备注： https://github.com/xmake-io/xmake-vscode/issues/19 
启用codelldb：https://github.com/xmake-io/xmake-vscode/pull/20

**Comment by waruqi** [comment]
我刚改进了下插件，只要用户装了codelldb插件，xmake-vscode在mac下就会自动检测优先使用它，不需要额外的配置，不过如果用到了sourceMap，还是需要自己配置下的。
