### ISSUE TITLE
当使用set_targetdir设置输出目录后，在vscode中使用lanunch.json开启程序会报target program not found

### ISSUE THREAD

**Issue by ksgfk** [xmake-io/xmake-vscode#262]
### Xmake 版本

2.8.9

### 操作系统版本和架构

Windows 11 23H2

### 描述问题

首先在xmake.lua里用set_targetdir设置输出目录
```lua
target("test")
    set_kind("binary")
    add_files("src/*.cpp")
    on_load(function(target)
        import("core.project.config")
        target:set("targetdir", path.join(os.projectdir(), "bin", config.mode()))
    end)
```

编译工程

然后在vscode的launch.json里编辑启动信息
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "xmake",
      "request": "launch",
      "name": "test",
      "target": "test",
      "stopAtEntry": false,
      "terminal": "integrated",
      "args": []
    }
  ]
}
```
接着在vscode面板里按 运行 - 启动调试

就会出现
![image](https://github.com/xmake-io/xmake-vscode/assets/37179748/44aa8865-7a4b-4a9d-aefd-4332597f3cd7)

然后关掉它就会出现
![image](https://github.com/xmake-io/xmake-vscode/assets/37179748/ad22897c-09ca-4adf-9490-2d7c43d87e4c)

如果删掉set_targetdir，不设置输出目录，可以正常调试

### 期待的结果

希望在set_targetdir后也可以正常使用vscode内置的调试启动

### 工程配置

描述问题内附加的代码片段就是最小可复现

### 附加信息和错误日志

描述问题内图片已有错误信息

**Comment by waruqi** [comment]
> 然后在vscode的launch.json里编辑启动信息

这个插件不使用用户 launch.json，删了，插件内部会自动生成

**Comment by ksgfk** [comment]
> > 然后在vscode的launch.json里编辑启动信息
> 
> 这个插件不使用用户 launch.json，删了，插件内部会自动生成，然后点底下 toolbar 的 run/debug

ok，了解了
