### ISSUE TITLE
toolchain drop list improvement

### ISSUE THREAD

**Issue by Juvwxyz** [xmake-io/xmake-vscode#263]
### Is your feature request related to a problem? Please describe.

![toolchain下拉列表](https://github.com/xmake-io/xmake-vscode/assets/11924271/b193322f-54de-446e-855b-f99d1e73f454)
选择工具链的下拉列表排序太混乱了，找个自己想要的要找半天。
另外，它经常记不住我之前选的工具链，点个build它就用默认配置重新config一遍（尤其是重启vscode窗口之后）。

### Describe the solution you'd like

至少按字典序排列一下。能记住我之前的config配置就更好了。

**Comment by waruqi** [comment]
排序了
