### ISSUE TITLE
xmake-vacode buildrun Bugs

### ISSUE THREAD

**Issue by PolarLinDa6** [xmake-io/xmake-vscode#265]
### Xmake 版本

2.9.1

### 操作系统版本和架构

Windows 11 version 23H2

### 描述问题

作者你好, 我在使用xmake-vscode 插件 xmake.onBuildRun 功能的时候遇到了一些问题

1. 构建失败后, 仍会执行上次生成的可执行文件
![问题1](https://github.com/xmake-io/xmake-vscode/assets/101777164/a9e674a8-3461-429f-9b05-1b8bd34a0420)

2. all target 时, 会执行xmake run all 而非 xmake run --all, 致使运行失败 
![问题2](https://github.com/xmake-io/xmake-vscode/assets/101777164/f8315ac5-63bf-40b9-adab-a06f042d1d59)

### 期待的结果

1. 构建失败后, 停止后续 run 操作
![屏幕截图 2024-05-11 214753](https://github.com/xmake-io/xmake-vscode/assets/101777164/26ed4e1d-f926-4b3f-b734-5bbd7b57a3a6)

2. all target 时, 使用 xmake run --all 运行
![屏幕截图 2024-05-11 214844](https://github.com/xmake-io/xmake-vscode/assets/101777164/04a1ce17-7670-473f-8462-0240aa4ef94e)

### 工程配置

[xmake.lua.txt](https://github.com/xmake-io/xmake-vscode/files/15283024/xmake.lua.txt)

### 附加信息和错误日志

![屏幕截图 2024-05-11 215858](https://github.com/xmake-io/xmake-vscode/assets/101777164/2b17a44f-457e-4afe-b564-00ba6e828211)

**Comment by waruqi** [comment]
> 构建失败后, 仍会执行上次生成的可执行文件

没法复现，这边正常

> all target 时, 会执行xmake run all 而非 xmake run --all, 致使运行失败

这个修了，更新下插件

**Comment by PolarLinDa6** [comment]
> > 构建失败后, 仍会执行上次生成的可执行文件
> 
> 没法复现，这边正常
> 
> > all target 时, 会执行xmake run all 而非 xmake run --all, 致使运行失败
> 
> 这个修了，更新下插件

作者你好, 我尝试一个demo

1. 第一次 xmake.onBuildRun 生成输出 hello world 的可执行文件
2. 第二次 xmake.onBuildRun 构建失败, 执行旧可执行文件

![屏幕截图 2024-05-11 225707](https://github.com/xmake-io/xmake-vscode/assets/101777164/f55780d6-c443-4e79-96e6-548909f120b5)

[demo.zip](https://github.com/xmake-io/xmake-vscode/files/15283255/F.zip)

**Comment by waruqi** [comment]
buildRun 目前是两个独立的 process task ，build 出错暂时影响不到后面的 run ，并且不好改。。要么你直接 xmake.lua 里配，用 run 

https://[xmake](https://xmake.io/#/zh-cn/guide/build_policies?id=runautobuild).io/#/zh-cn/guide/build_policies?id=runautobuild

**Comment by PolarLinDa6** [comment]
> buildRun 目前是两个独立的 process task ，build 出错暂时影响不到后面的 run ，并且不好改。。要么你直接 xmake.lua 里配，用 run
> 
> https://[xmake](https://xmake.io/#/zh-cn/guide/build_policies?id=runautobuild).io/#/zh-cn/guide/build_policies?id=runautobuild

作者你好, 我已经开启了 runautobuild, 但是输出两次错误, 我是接受不了的

![屏幕截图 2024-05-11 234734](https://github.com/xmake-io/xmake-vscode/assets/101777164/6ad8ae37-6407-44f7-9de8-4ce33b29608b)

我尝试在 before_run 中停止第二次输出, 但是没有成功, 作者你可以帮助我吗
![image](https://github.com/xmake-io/xmake-vscode/assets/101777164/9ea8d483-0e7e-4764-9256-e48861094129)

**Comment by PolarLinDa6** [comment]
作者你好,  上面的问题已经完美解决了, 但我有一个问题, 无法解决您可以帮助我吗

有以下文件结构
- Test
  - xmake.lua **( Target("Demo1") + Target("Demo2") + ... )**
  - Demo1.cpp
  - Demo2.cpp
  ...
- Main.cpp
- xmake.lua **( target("Main") + include("Test") )**

我想要实现一个 target("All_Demo"), 他会对 Test 内的每个cpp文件进行构建, 生成多个可执行文件, 并调用

**Comment by PolarLinDa6** [comment]
> buildRun 目前是两个独立的 process task ，build 出错暂时影响不到后面的 run ，并且不好改。。要么你直接 xmake.lua 里配，用 run
> 
> https://[xmake](https://xmake.io/#/zh-cn/guide/build_policies?id=runautobuild).io/#/zh-cn/guide/build_policies?id=runautobuild

作者你好, 我已经开启了run.autobuild, 但是当我选择 target: Test_Demo 时,  他好像不会 run前自动构建
![image](https://github.com/xmake-io/xmake-vscode/assets/101777164/b2c686d3-abca-49c8-b80b-e2f94f057155)

如图: 他提示我需要需要手动构建一次
![](https://github.com/xmake-io/xmake-vscode/assets/101777164/47437103-c1fb-4363-b736-528a23d53798)

如图: 第一次我尝试输出 "first", 第二次我尝试输出 "second", 但是它仍输出 
![屏幕截图 2024-05-12 131845](https://github.com/xmake-io/xmake-vscode/assets/101777164/67780eaf-cb8f-4e69-a8f3-4b59f16dda35)

 [Demo.zip](https://github.com/xmake-io/xmake-vscode/files/15285168/Demo.zip)

**Comment by waruqi** [comment]
再试试，xmake update -s dev

**Comment by PolarLinDa6** [comment]
> 再试试，xmake update -s dev

抱歉作者, 是我说错了, 在 all target 下才会出现的, 对不起


![屏幕截图 2024-05-12 232721](https://github.com/xmake-io/xmake-vscode/assets/101777164/90965f0f-6edf-40b6-875b-295fdcdf1fb9)

**Comment by waruqi** [comment]
再试试 xmake update -s dev，如果代码没改动，不会构建

**Comment by PolarLinDa6** [comment]
> 再试试 xmake update -s dev，如果代码没改动，不会构建

当我将  target:Test_Demo 的 set_default(false) 改为 set_default(true) 之后, 这个问题成功解决了
PS:  set_default(false) 下, 代码即使改动了, 仍然不会构建, 希望作者可以修复

**Comment by waruqi** [comment]
这边可以，没法复现

```console
ruki-2:Demo ruki$ xmake run -a
[ 37%]: cache compiling.debug Test/Demo.cpp
[ 87%]: linking.debug Test_Demo
[100%]: build ok, spent 1.143s
mainruki-2:Demo ruki$ touch Test/Demo.cpp
ruki-2:Demo ruki$ xmake run -a
[ 37%]: cache compiling.debug Test/Demo.cpp
[ 87%]: linking.debug Test_Demo
[100%]: build ok, spent 0.421s
```

**Comment by PolarLinDa6** [comment]
> 这边可以，没法复现
> 
> ```
> ruki-2:Demo ruki$ xmake run -a
> [ 37%]: cache compiling.debug Test/Demo.cpp
> [ 87%]: linking.debug Test_Demo
> [100%]: build ok, spent 1.143s
> mainruki-2:Demo ruki$ touch Test/Demo.cpp
> ruki-2:Demo ruki$ xmake run -a
> [ 37%]: cache compiling.debug Test/Demo.cpp
> [ 87%]: linking.debug Test_Demo
> [100%]: build ok, spent 0.421s
> ```

我重新试了demo, 发现也无法复现( 我也不知道为什么 )
最后感谢作者的解答, 祝作者生活快乐
