### ISSUE TITLE
vscode插件 debug 启动不了

### ISSUE THREAD

**Issue by KarryCharon** [xmake-io/xmake-vscode#266]
### Xmake 版本

2.9.1

### 操作系统版本和架构

windows10

## vscode的xmake 插件 bug
1. 底部 debug 按钮启动不了 提示 Target program not found.
2. 通过调试配置也启动不了 提示 launch: property 'program' is missing or empty.

### 期待的结果

-

### 工程配置

`xmake.lua`: 
```lua
add_rules("mode.debug", "mode.release")

target("hello")
    add_files("hello.cpp")
```
`.vscode/launch.json` :
```json

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "xmake",
            "request": "launch",
            "name": "Launch",
            "target": "hello",
            "cwd": "xxx",
            "stopAtEntry": true
        }
    ]
}
```

### 附加信息和错误日志

-

**Comment by waruqi** [comment]
不需要 .vscode/launch.json ，删了
