### ISSUE TITLE
插件中增加 buildDebug

### ISSUE THREAD

**Issue by PolarLinda6** [xmake-io/xmake-vscode#271]
### 你在什么场景下需要该功能？

调试时, 每次改动代码后都需要先编译, 才能开始新的调试, 希望可以增加开始调试时自动编译的选项

### 描述可能的解决方案

xmake 增加类似 run.autobuild 的 debug.atuobuild 功能 , 或者在插件中增加 xmake.onbuildDebug 命令

**Comment by PolarLinda6** [comment]
作者你好, 指定 buildRun 可以解决这个问题,  但是会引入其他问题:

1. xmake.onRun 时, 先编译报错一次,  运行再报错一次, 两次错误完全一样( 如图 )

> PS: 指定  "xmake.runMode": "runOnly",  policies = "run.autobuild" 可以解决这个问题, 但是无法实现 启动调试时自动编译
![image](https://github.com/user-attachments/assets/bbb9dbe1-1e1f-4002-b6e0-d87bbd620481)

2. 启动调试时, 即便编译失败, 仍会开始调试( 如图 )
![image](https://github.com/user-attachments/assets/79e7a4ae-307a-4026-8dc0-7bae6b938176)
![image](https://github.com/user-attachments/assets/d11955ea-db6f-4d67-8f52-93daa2341528)

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-vscode/issues/268#issuecomment-2254368465
