### ISSUE TITLE
调试功能出错：Please specify the "MIDebuggerPath" option

### ISSUE THREAD

**Issue by KB5201314** [xmake-io/xmake-vscode#30]
### 描述问题

任意新建一个xmake c++项目，然后使用vscode打开项目，点击底部xmake-vscode插件的调试按钮后出错，编译成功，但调试无法进行

### 期待的结果

开始调试程序

### 错误信息

![图片](https://user-images.githubusercontent.com/14936301/77985695-ba148280-7347-11ea-863e-d2c7943ab388.png)

### 相关环境

Manjaro Linux x86_64
Code - OSS 1.43.2
xmake v2.3.1+202003121446

### 其他信息

无

**Comment by waruqi** [comment]
vscode的 c++ tools插件装了没有

**Comment by KB5201314** [comment]
> vscode的 c++ tools插件装了没有
装了Microsoft自己的的C/C++插件

**Comment by waruqi** [comment]
那应该没问题的才对，你是切到debug编译的程序么。不行你就自己加载 xmake-vscode源码 点调试运行跟下吧。。我这边暂时没 linux的 pc 环境，也调不了。

**Comment by KB5201314** [comment]
就很迷，还是算了，先gdb凑合一下

**Comment by waruqi** [comment]
看着是cpptools这个插件在你这没找到gdb的路径，具体可以看下这里面的解决方案：https://github.com/microsoft/vscode-cpptools/issues/2971#issuecomment-450039730

通过which gdb找下你这真实的gdb安装路径，然后通过 vscode的xmake.customDebugConfig配置 重写写内部miDebuggerPath的 gdb 路径，试试

```
"xmake.customDebugConfig": {
  "miDebuggerPath": "xxxxxx/gdb"
}
```

**Comment by KB5201314** [comment]
抱歉，是我的锅，才发现我没装gdb，装上就没有这个警告了。
另外，该解决方案中提到的另一个问题，通过设置`"externalConsole": false`在我的Manjaro上能够解决，现在已经能调试。
现在看来我在提问前应该先考虑从vscode自身找解决方案
非常感谢
