### ISSUE TITLE
无法调试

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake-vscode#33]
test.cpp
```
#include <iostream>

int main()
{
    std::cout << "Hello, world!" << std::endl;
    return 0;
}
```
用工具栏操作，点击编译和运行都可以，但是点击调试不行（无限等待），截图：
![2020-05-19_23-14](https://user-images.githubusercontent.com/3665590/82344923-37df3b00-9a27-11ea-9177-353794ce9cf6.png)

Version Info
* XMake (vscode plugin): 1.3.4
* VSCodium (variant of vscode): 1.45.1
* OS: Manjaro

**Comment by waruqi** [comment]
你点的哪个调试？看下readme里面的演示图片，点底下toolbar里面的bug button调试按钮

并确保c/c++ vscode插件也装了

**Comment by playgithub** [comment]
![2020-05-19_23-39](https://user-images.githubusercontent.com/3665590/82347505-4aa73f00-9a2a-11ea-8b43-824fd386ea66.png)
![2020-05-19_23-40](https://user-images.githubusercontent.com/3665590/82347509-4c710280-9a2a-11ea-92b5-0b8894af5740.png)
是这样的，不能调试

**Comment by waruqi** [comment]
gdb装了么？录个屏我看下呢？

**Comment by playgithub** [comment]
```
$whereis gdb
gdb: /usr/bin/gdb /etc/gdb /usr/include/gdb /usr/share/gdb /usr/share/man/man1/gdb.1.gz /usr/share/info/gdb.info.gz
```

```
whereis lldb
lldb: /usr/bin/lldb /usr/include/lldb /usr/share/man/man1/lldb.1.gz
```

**Comment by playgithub** [comment]
用的VSCodium，我马上用vscode试一下

**Comment by playgithub** [comment]
![image](https://user-images.githubusercontent.com/3665590/82349555-d621cf80-9a2c-11ea-967b-8db8b97d45a2.png)
vscode也一样不行，箭头所指进度条无限循环

**Comment by waruqi** [comment]
调试前，main入口断点下了么。。

> BTW, 之前用Lua Debug调试lua的hello world也是这样。

这个跟xmake没啥关系吧，如果其他插件也带不起调试，那我就不清楚了

我现在也没linux的可视化环境，要么你直接clone下代码，用vscode打开项目根目录，然后点加载运行，帮忙调下插件里面debugger.ts地方，也没几行代码。

**Comment by playgithub** [comment]
> 调试前，main入口断点下了么。。

没有main，就一句 print("hello")

> 我现在也没linux的可视化环境，要么你直接clone下代码，用vscode打开项目根目录，然后点加载运行，帮忙调下插件里面debugger.ts地方，也没几行代码。

vscode插件零经验，上手有点麻烦，用不用vscode还不一定，我还是先学习xmake再说吧。

**Comment by waruqi** [comment]
> 调试前，main入口断点下了么。。
> 没有

需要自己现在main入库设置好断点，才能点调试运行，进行断点调试，你加上试试，如果还是不行 我现在也没环境给你调试，之前测试过 断点调试应该没问题的。

**Comment by playgithub** [comment]
加了，不行

**Comment by waruqi** [comment]
那就不知道了

**Comment by playgithub** [comment]
用launch.json，路径固定可以调试，先这样了，也不麻烦。

**Comment by waruqi** [comment]
> 用launch.json，路径固定可以调试，先这样了，也不麻烦。

既然launch.json可以了，那就帮忙对比下插件内置的launch.json配置差异，看下是那个配置不对导致的呗。。我也好改进下插件

https://github.com/xmake-io/xmake-vscode/blob/ab6032f80ab568d5c479f78614840900b8ba1e3f/src/debugger.ts#L87-L103

**Comment by playgithub** [comment]
launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "/path/to/linux/x86_64/debug/test",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

**Comment by waruqi** [comment]
```
            "program": "/path/to/linux/x86_64/debug/test",
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "externalConsole": false,
```

```
         program: targetProgram, 
         stopAtEntry: true, 
         cwd: targetRunDir, 
         externalConsole: true, 
```

主要就是这四个的差异，你可以先在你这里的launch.json里面吧 stopAtEntry/externalConsole设置成False，排除下这两个，如果这两没问题，多半是传入program的path有问题导致。。

可以git clone下xmake-vscode的源码，用vscode打开根目录，

在xmake.ts的下面代码块最后加上

```js
        log.info("targetName: " + targetName);
        log.info("targetProgram: " + targetProgram);
```

https://github.com/xmake-io/xmake-vscode/blob/ab6032f80ab568d5c479f78614840900b8ba1e3f/src/xmake.ts#L704-L712

然后点调试运行，在output里面给我看下输出，基本上就能查出原因了

**Comment by playgithub** [comment]
先这样，打算先学一下vscode插件和xmake。

**Comment by waruqi** [comment]
可以看下这个，https://github.com/xmake-io/xmake-vscode/issues/36   人家应该找到问题原因了，你可以试试最新版本

**Comment by littlewater** [comment]
从这里来看貌似使用F5好像还是不支持，F5默认是调用的launch.json，编辑launch.json的方法意义不大，毕竟多个配置不可能一个个去改动的。

**Comment by waruqi** [comment]
不用自己编辑launch.json，xmake-vscode内置传递了 launch.json，只需要点 工具栏最下面，xmake-vscode插件提供的调试按钮就行了。。f5等快捷键我暂时没加
