### ISSUE TITLE
the debug button does not work as expected

### ISSUE THREAD

**Issue by caizongchao** [xmake-io/xmake-vscode#36]
After clicking the debug button (Debug the give target), the vscode debug toolbar appears but the program does not break at the entry point or any other break points.

After some investigation, I found that changing debugConfig externalConsole to false (in ...\out\src\debugger.js) makes the debugger working properly (I have microsoft cpp tools installed):

```
            else if (os.platform() == "linux") {
                    debugConfig = {
                       ...
                        // externalConsole: true,
                       externalConsole: false,
                       ...
                    };
```

**Comment by waruqi** [comment]
I have merged this patch, you can update xmake-vscode and try it again.

**Comment by a5066987** [comment]
我用Remote-WSL也有这个问题，看版本应该是已经更新过的了。调试的界面一闪而过
![image](https://user-images.githubusercontent.com/13390857/82742253-9a2e8900-9d10-11ea-977d-0b8ec5344c67.png)
