### ISSUE TITLE
有没有办法得到编译目标的路径

### ISSUE THREAD

**Issue by playgithub** [xmake-io/xmake-vscode#39]
比如`...\test_lib\build\windows\x64\debug\test_lib_demo.exe`，可以的话就可以很方便地集成到vscode，从而利用vscode的调试机制
如果不行，加一个`xmake get_config target_path`怎么样？

**Comment by waruqi** [comment]
> 想用快捷键

目前不支持，直接点下面的调试图标 也很省事

**Comment by waruqi** [comment]
> BTW, M$调试器不支持vscode，xmake-vscode能让M$调试器支持调试吗？

为什么不支持，我之前试过，可以在win下调试，用的就是 cppvsdbg

https://github.com/xmake-io/xmake-vscode/blob/289d7b81ab8409e011255425cf5f3fb727be5016/src/debugger.ts#L104-L119

**Comment by waruqi** [comment]
linux下之前也有遇到卡住问题，可以参考这个：https://github.com/xmake-io/xmake-vscode/issues/36

通过自定义配置，覆盖内部的 externalConsole 到 false， 看下 是否ok

**Comment by playgithub** [comment]
> > 想用快捷键
> 
> 目前不支持，直接点下面的调试图标 也很省事



> > BTW, M$调试器不支持vscode，xmake-vscode能让M$调试器支持调试吗？
> 
> 为什么不支持，我之前试过，可以在win下调试，用的就是 cppvsdbg

哦，说错了，vscode支持，vscodium不支持，M$就是要telemetry

**Comment by playgithub** [comment]
> linux下之前也有遇到卡住问题，可以参考这个：#36
> 
> 通过自定义配置，覆盖内部的 externalConsole 到 false， 看下 是否ok

我都想vim+xmake了，喜欢简单的
