### ISSUE TITLE
支持为vscode-cpptools提供intellisense配置信息

### ISSUE THREAD

**Issue by u3IFw2wfJ** [xmake-io/xmake-vscode#40]
VS Code的c++插件有一个配置提供程序的选项，可以使用第三方工具提供intellisense的配置信息：
![image](https://user-images.githubusercontent.com/32400590/86529436-89237c80-be65-11ea-9d58-c22647e89211.png)

xmake有可能对这个地方做适配吗，感觉这样会方便很多

**Comment by waruqi** [comment]
目前还不支持，主要是最近没太多时间去研究和支持这块

如果你感兴趣，可以帮忙提个pr上来，或者帮忙提供一些如何支持的相关文档或者可供参考的example，如果支持起来不麻烦，我会考虑的

**Comment by u3IFw2wfJ** [comment]
> 目前还不支持，主要是最近没太多时间去研究和支持这块
> 
> 如果你感兴趣，可以帮忙提个pr上来，或者帮忙提供一些如何支持的相关文档或者可供参考的example，如果支持起来不麻烦，我会考虑的

我找了一下，没找到相关的文档。但是看了下cpptools的代码，感觉应该是要实现一个`CustomConfigurationProvider`接口，大概在这个位置
![image](https://user-images.githubusercontent.com/32400590/86544650-7ba9d900-bedd-11ea-8a23-cf5b0949b7ce.png)

cpptools里面的相关实现在`src/LanguageServer/customProviders.ts`和`src/LanguageServer/configurations.ts`里。不过我不会写typescript，很多地方看不懂......

**Comment by waruqi** [comment]
嗯，等有时间我看下。

**Comment by waruqi** [comment]
你可以参考这个，配置下 c_cpp_properties.json 
https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference

里面设置下 compile_commands.json的路径就好，而xmake支持生成这个的

```console
xmake project -k compile_commands
```

插件内置支持，我会有有时间了 会考虑改进下。不过你先手动这样配置下，应该也能用。

**Comment by waruqi** [comment]
我插件更新了下，支持自动生成 compile_commands.json 到当前项目的 .vscode 目录下，如果你要支持intellisense，只需要配置 .vscode/c_cpp_properties.json在里面关联上这个 .vscode/compile_commands.json 路径就行了

至于，具体怎么生成c_cpp_properties，官方文档里面有详细说明：https://code.visualstudio.com/docs/cpp/configure-intellisense-crosscompilation



```
for example (.vscode/c_cpp_properties.json):

  "configurations": [
    {
      "compileCommands": ".vscode/compile_commands.json",
    }
  ],
}
```

**Comment by u3IFw2wfJ** [comment]
测试了一下，可以正常显示intellisense信息了

**Comment by wuzhiguocarter** [comment]
非常赞的功能

**Comment by OuYangPaste** [comment]
very very good

**Comment by waruqi** [comment]
我新加了一个 xmake.onUpdateIntellisense 的命令，可以手动执行去强制触发 compile_commands.json 的更新

**Comment by yueneiqi** [comment]
> 我新加了一个 xmake.onUpdateIntellisense 的命令，可以手动执行去强制触发 compile_commands.json 的更新

我查文档没有找到这个命令的使用，能再解释一下怎么用吗？谢谢

**Comment by OuYangPaste** [comment]
> 我查文档没有找到这个命令的使用，能再解释一下怎么用吗？谢谢
这是 vscode 插件的命令，在vscode 里 ctrl + shift + p 输入这个命令
![image](https://user-images.githubusercontent.com/38561133/167752189-e6427129-e457-4457-be34-19853211d914.png)

**Comment by DawnMagnet** [comment]
这个插件生成的似乎有些问题，我需要编译QString/QtCore的相关头文件，但并没有找到
<img width="810" alt="image" src="https://user-images.githubusercontent.com/61567130/171103396-a916d5a5-72fb-4415-8010-9ddb7d539661.png">
这个显示xmake是可以找到安装在本地的Qt6相关的库
根据上述命令生成compile_commands.json之后
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/61567130/171103558-2b777ecf-f6cd-4a84-bb14-154d6d6ba6cf.png">
可以看到，并没有qt相关库的地址
所以C/C++ Extension中的Intellisense并没有被正确配置

**Comment by waruqi** [comment]
更完整的配置说明，我更新到文档了，可以直接看文档：https://xmake.io/#/zh-cn/plugin/more_plugins?id=%e9%85%8d%e7%bd%ae-intellsence
