### ISSUE TITLE
第三方依赖的头文件查找路径

### ISSUE THREAD

**Issue by compilelife** [xmake-io/xmake-vscode#43]
### 你在什么场景下需要该功能？

require了第三方库，include第三方头文件，但是vscode提示找不到（编译是没问题）

### 描述可能的解决方案

是不是可以通过解析第三方库的include路径，然后自动添加到vscode的c++ include path里？

### 描述你认为的候选方案

无

### 其他信息

无

**Comment by waruqi** [comment]
看下 https://github.com/xmake-io/xmake-vscode/issues/40

**Comment by Aragaki-Iwa** [comment]
你好，请问如果采用了 add_requires的方式 来使用远程包，应该怎样 include 第三方库的头文件呢，因为第三方库的路径在  /home/username/.xmake/packages 下 难道要 add_includedirs(“/home/username/.xmake/packages ”)吗？应该有别的方法吧，没有找到相关的解决方法，或者说只能安装在 /use/local/lib 下吗？

**Comment by waruqi** [comment]
不用管 啥也不用干 配了 intelligense 原本就支持

**Comment by zong4** [comment]
对啊，必须得设置public=true才行，但是这样不是上层也能看到了吗
