### ISSUE TITLE
VSCode使用xmake插件创建项目出错

### ISSUE THREAD

**Issue by PengChuan98** [xmake-io/xmake-vscode#44]
在windows10，2004企业版下使用VSCode创建 qt.widgetapp 项目出现错误
```bat
> Executing task: xmake create -t qt.widgetapp -l c++ -P c:\temp\demo <

create demo ...
error: project directory (C:\temp\demo) is not empty!
The terminal process "C:\Windows\System32\cmd.exe /d /c xmake create -t qt.widgetapp -l c++ -P c:\temp\demo" failed to launch (exit code: 4294967295).

Terminal will be reused by tasks, press any key to close it.
```
在执行之前确认文件夹为空
```bat
C:\Users>xmake l os.emptydir "c:\temp\demo"
true
```

**Comment by waruqi** [comment]
那就不知道了，你可以执行 xmake update -s dev 更新脚本后，在自己的安装目录下编辑这个位置的代码 加点 print 调下。。

https://github.com/xmake-io/xmake/blob/825867bd8870f118fd052d8a8407fce839e158ed/xmake/actions/create/main.lua#L85

**Comment by PPika** [comment]
> 那就不知道了，你可以执行 xmake update -s dev 更新脚本后，在自己的安装目录下编辑这个位置的代码 加点 print 调下。。
> 
> https://github.com/xmake-io/xmake/blob/825867bd8870f118fd052d8a8407fce839e158ed/xmake/actions/create/main.lua#L85

hhh，麻烦您了，我这里看看源码是不是有问题，今天这是多谢了。

**Comment by waruqi** [comment]
应该修了

**Comment by PengChuan98** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
