### ISSUE TITLE
vscode中调试源码的问题

### ISSUE THREAD

**Issue by LovingXiaobing** [xmake-io/xmake-vscode#45]
调试使用不了。

下面是我的操作步骤：
xmake create -l c -t console test
cd test
xmake f -p msys  -a x86_64 -m debug --toolchain=clang
code .
vscode打开后，点击vscode状态栏中xmake的"Build"选项成功编译。
在源文件中下一个有效的断点。
![image](https://user-images.githubusercontent.com/40991112/92383368-c693d700-f140-11ea-95b7-4a96c7ef74d3.png)
点击vscode状态栏中xmake的"调试按钮
![image](https://user-images.githubusercontent.com/40991112/92383431-e2977880-f140-11ea-9f2d-625c1a9a0360.png)
"来调试程序。

![image](https://user-images.githubusercontent.com/40991112/92383778-7ff2ac80-f141-11ea-9aa1-92243fd6d6e6.png)

并不能像readme所展示的那样，就可以直接启用调试。我之后得自己配置launch.json来自己配置调试器。

请问xmake的vscode插件有什么便利的方法来调试程序吗？
当然我理想中，只要配置好xmake.lua，在vscode中就可以自己完成intelligence或者debug的相关配置。

谢谢。

**Comment by waruqi** [comment]
win上vscode加载调试目前仅支持msvc编译器，因为需要pdb符号文件，mingw和clang都不支持生成pdb文件，要么使用clang-cl 

所以想调试，就走msvc，不用特地切平台和clang

**Comment by LovingXiaobing** [comment]
> win上vscode加载调试目前仅支持msvc编译器，因为需要pdb符号文件，mingw和clang都不支持生成pdb文件，要么使用clang-cl
> 
> 所以想调试，就走msvc，不用特地切平台和clang

知道了，谢谢你。
