### ISSUE TITLE
支持为qt项目提供完善的intellisense

### ISSUE THREAD

**Issue by Itsusinn** [xmake-io/xmake-vscode#47]
我已经使用过`xmake project -k compile_commands`生成compile_commands.json文件
但是intellisense无法识别*.ui生成的ui_*.h文件
推测是compile_commands.json的includePath不含ui_*.h

**Comment by Itsusinn** [comment]
ui_*.h是build后产生的，使intellisense正常工作看起来很困难

**Comment by waruqi** [comment]
这块还不支持，等回头有时间再看看好了。

**Comment by waruqi** [comment]
最近几个版本 xmake 应该已经支持生成带 qt 的 compile_commands 了
