### ISSUE TITLE
能否为package增加intellisense支持

### ISSUE THREAD

**Issue by Biobots** [xmake-io/xmake-vscode#48]
### 你在什么场景下需要该功能？

`add_package`添加的package能够在vscode中显示intellisense信息

### 描述可能的解决方案

目前似乎都是在编译或者手动`require`时才会编译package，这样的话感觉没法实现根据`xmake.lua`中的package信息来支持intellisense？

**Comment by waruqi** [comment]
集成了package，编译的项目里面，不是package includedirs都带进去了么。。那么安装package之后，生成的 compile_commands.json 里面应该也是有 package includedirs的。。

比如我这：`-I/Users/ruki/.xmake/packages/l/luaj
it/2.1.0-beta3/d31cb26efe584bfab3db002ca62988af/include/luajit`

```
{
  "directory": "/Users/ruki/share/testdll",
  "arguments": ["/usr/local/bin/ccache", "/usr/bin/xcrun", "-sdk", "macosx", "clang", "-c", "-f
visibility=hidden", "-fvisibility-inlines-hidden", "-O3", "-I/Users/ruki/.xmake/packages/l/luaj
it/2.1.0-beta3/d31cb26efe584bfab3db002ca62988af/include/luajit", "-Qunused-arguments", "-arch",
 "x86_64", "-mmacosx-version-min=10.14", "-isysroot", "/Applications/Xcode.app/Contents/Develop
er/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk", "-o", "build/.objs/testdll/macosx
/x86_64/release/src/main.cpp.o", "src/main.cpp"],
  "file": "src/main.cpp"
},
```

这个插件已经对接了 intellisense / compile_commands（具体见 https://github.com/xmake-io/xmake-vscode/issues/40），怎么会不支持呢？

**Comment by Biobots** [comment]
确实看见includedirs了，可能是我这插件配置有问题，我再看一下看
