### ISSUE TITLE
Ubuntu18.04，helloWorld 在vscode中使用xmake_vscode无法调试

### ISSUE THREAD

**Issue by Ultraman95** [xmake-io/xmake-vscode#5]
使用xmake build
xmake run 可以正常使用

在vscode中使用xmake rebuild，然后debug，报错
Stopping due to fatal error: NullReferenceException: Object reference not set to an instance of an object

同时一个新的terminal被自动打开，zsh无法被加载，我的terminal用的是zsh

**Comment by waruqi** [comment]
我这边暂时没有linux gui的系统，你可以先自己下载xmake-vscode的源码 用vscode加载帮忙调下

或者等后面有时间的时候，我在装个环境试试，不过可能会等上一段时间

**Comment by waruqi** [comment]
我这边测了下 ubuntu+vscode环境，这边测试正常, bash+gdb调试，以及c++源码调试都ok

你可以装下vscode的c/c++插件，源码单步调试依赖这个插件。

**Comment by waruqi** [comment]
无法复现，这里先close了 回头有问题继续开issues 另外我后来更新过插件 可以再试试 是否还有这问题
