### ISSUE TITLE
Windows Debugging Doesn't Use Configured Arguments

### ISSUE THREAD

**Issue by wrren** [xmake-io/xmake-vscode#51]
### Describe the bug

The debugger uses `xmake.debuggingTargetsArguments` in order to set up the arguments for a debugging session correctly on most platforms, however when debugging on Windows these settings are ignored, and an empty argument list is used instead.

### Expected behavior

Debugging on Windows should use arguments from the `xmake.debuggingTargetsArguments`, as is expected on other platforms.

### Error output

None. Arguments are simply not used during debugging.

### Related Environment

- xmake version: v2.3.6+202007281022
- os: Windows 10 x64
- target platform: Windows x64

**Comment by waruqi** [comment]
Thank you very much for your contribution, I have merged this patch and released a new version. v1.4.1
