### ISSUE TITLE
Can't debug with msys2 gdb in VSCode UI

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake-vscode#53]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

![image](https://user-images.githubusercontent.com/42310255/97106569-7f1bd700-16fd-11eb-89d3-8c5b4774e070.png)
如图所示，用VS Code+Msys2 gdb时点击debug按钮没有UI提示，断点也没有作用。

### 期待的结果

有debug UI提示

### 错误信息

没有错误信息
> 如果是xmake相关编译问题，请加上`-vD`参数运行，并给出详细编译输出信息。

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：2.3.8
- xmake运行平台：Windows 10
- xmake目标平台：mingw

### 其他信息

项目配置就是默认`xmake create`产生的，只在`main.cpp`中加了几行。

命令行`xmake r -d`没有问题，用Visual Studio调试也没有问题。

**Comment by waruqi** [comment]
mingw不支持生成pdb，而win上xmake-vscode插件走的msvc的调试器，肯定加载不起来

要么切到llvm-mingw试试，这个支持pdb生成，或者xmake-vscode自定义配置切到gdb调试器，不过我估计多半在win上也不一定支持

**Comment by xq114** [comment]
> mingw不支持生成pdb，而win上xmake-vscode插件走的msvc的调试器，肯定加载不起来
> 
> 要么切到llvm-mingw试试，这个支持pdb生成，或者xmake-vscode自定义配置切到gdb调试器，不过我估计多半在win上也不一定支持

![image](https://user-images.githubusercontent.com/42310255/97129937-0eb39b00-177b-11eb-9a56-abf7c9c47197.png)
VSCode C/C++扩展是可以正常调试msys2程序的，能不能参考下他们这个做法，似乎是切到terminal然后运行WindowsDebugLauncher.exe

**Comment by waruqi** [comment]
> VSCode C/C++扩展是可以正常调试msys2程序的，能不能参考下他们这个做法，似乎是切到terminal然后运行WindowsDebugLauncher.exe

xmake-vscode 原本就是用的 C/C++扩展的调试功能，估计顶多是传给他们的 launch 配置目前没设置 msys 相关的参数。

你可以参考 https://github.com/xmake-io/xmake-vscode/blob/master/src/debugger.ts 自己改下

https://github.com/xmake-io/xmake-vscode/blob/f6b62786c95edfa806595e43008ef84a12d7717d/src/debugger.ts#L104-L120

这块的配置，也可以在插件自定义配置 "xmake.customDebugConfig" 中，用户自己重写覆盖内部设置。

关于如何重写，你可以参考：https://github.com/xmake-io/xmake-vscode/issues/19

我现在没有 win/msys环境，暂时调不了这块，你可以自己尝试重写内部调试配置，也可以直接通过vscode加载插件源码，自己改下debugger.ts帮忙改进下对msys/mingw调试的支持
