### ISSUE TITLE
Debug session pause on entry

### ISSUE THREAD

**Issue by jprochazk** [xmake-io/xmake-vscode#55]
When starting a debugging session with `XMake: Debug`, the program is paused on entry. Is there a way to disable this behavior? If there isn't, it would be nice to add this option. In programs debugged with gdb/lldb/etc, in the `launch.json` configuration, you can set the `stopOnEntry` field. Because XMake is not run through `launch.json`, I think it would be reasonable.

If it is okay, I could submit a PR for this.

**Comment by waruqi** [comment]
You can set `xmake.customDebugConfig` in settings to rewrite the given launch.json configuration item. for example

```
"xmake.customDebugConfig": {
  "sourceMap": {
    "../../src": "xxxx/xxxx/xxx/src"
  }
, "stopOnEntry": false
}
```

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-vscode/blob/32ab272b7b63c7086cd59364699b15818fdbd5bb/src/debugger.ts#L142-L145

**Comment by jprochazk** [comment]
> You can set `xmake.customDebugConfig` in settings to rewrite the given launch.json configuration item. for example

This works. I made a mistake, it's `stopAtEntry` instead of `stopOnEntry`. Is this documented anywhere? I couldn't find it. Thank you for the help!

**Comment by waruqi** [comment]
no document now. :(
