### ISSUE TITLE
compile_commands.json 没有自动生成

### ISSUE THREAD

**Issue by junknet** [xmake-io/xmake-vscode#56]
windows平台
按照入门指导建立了一个工程.
啥都是最新版

**Comment by waruqi** [comment]
目前只有 xmake.lua 有改动才会自动更新生成，如果还是没有，就自己clone xmake-vscode源码，用vscode 加载调试下吧，我暂时没win/vscode环境

https://github.com/xmake-io/xmake-vscode/blob/32ab272b7b63c7086cd59364699b15818fdbd5bb/src/xmake.ts#L193-L207

**Comment by junknet** [comment]
OK

**Comment by waruqi** [comment]
这个问题应该已经修复了，你可以再试试
