### ISSUE TITLE
Cannot find ".vscode\compile_commands.json".

### ISSUE THREAD

**Issue by RussellHaley** [xmake-io/xmake-vscode#57]
Hi again,

Windows 10 
xmake v2.3.8+202011211435
llvm-mingw
vscode 1.51.1

I'm just trying out the vscode add-in. Your instructions indicate a compile_commands.json file is generated when xmake is installed but I don't have that file in my .vscode directory? I added a reference to that file in my c_cpp_properties.json file as noted in the README:

```
{
    "configurations": [
        {
            "name": "Win32",
            "compileCommands": ".vscode/compile_commands.json",
            "includePath": [
                "${workspaceFolder}/**",
                "C:\\Program Files (x86)\\WinLua\\Lua\\5.3\\include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "C:\\Users\\russh\\llvm-mingw\\bin\\clang.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}

```

Which generates the following error:
```
Cannot find ".vscode\compile_commands.json".
```

Not a big deal, I'm just trying things out. Thanks!

Russ

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-vscode/blob/32ab272b7b63c7086cd59364699b15818fdbd5bb/src/xmake.ts#L193-L205

The compile_commands.json file will only be generated when the xmake.lua file is changed. You can try to modify the xmake.lua file.

Sorry, I don’t have a windows+vscode environment. If this problem still exists, you can use vscode to open the xmake-vscode project source code, load and run it, and debug the following code.

**Comment by waruqi** [comment]
@jprochazk tried to fix it, you can try it again. I have uploaded v1.4.3 to vscode market.

**Comment by RussellHaley** [comment]
The update was in the extensions window when I opened VS Code. I accepted the update and it restarted the project. It wouldn't compile right away. I changed a cpp file and compile_commands.json showed up. I couldn't get it to build until I restarted again, but I think that was my fumbling.

Xmake works as expected. Adding a new file to the project and to xmake.lua works (new entry in compile_comanes.json). The keymaps don't change from the defaults. To change the key mappings: Manage (Gear icon, bottom left) -> Keyboard Shortcuts. Type "xmake:" then change the shortcut.  Is it possible to re-arrange keymaps in a VSCode extension?

I changed:
New window ctrl+shift+n -> ctrl + alt + n (re-assigned)
Build Task -> (removed)
xmake: build -> ctrl+shift+b (same as Visual Studio)
xmake: clean -> ctrl+shift+n
xmake: run  -> shift + .

Thanks Ruki, @jprochazk.

**Comment by waruqi** [comment]
>  Is it possible to re-arrange keymaps in a VSCode extension?

Currently you can only modify the key mapping manually. refer https://github.com/xmake-io/xmake-vscode/issues/50#issuecomment-723367580

> File > Preferences > Keyboard Shortcuts, write xmake into the search bar, find XMake: Debug, right click it and click Change Keybinding
