### ISSUE TITLE
调试时提示：Unable to start debugging. Unexpected LLDB output from command "-interpreter-exec console "version"". Undefined command: "version".  Try "help".

### ISSUE THREAD

**Issue by huangqi329** [xmake-io/xmake-vscode#58]
环境：macos 11
xmake及插件都是安装的最新版本，编译并启动调试时提示如下：
Unable to start debugging. Unexpected LLDB output from command "-interpreter-exec console "version"". Undefined command: "version".  Try "help".

![image](https://user-images.githubusercontent.com/49861888/100564818-07912700-32fd-11eb-8591-0d85fc828afb.png)

**Comment by waruqi** [comment]
是从最底下工具栏按钮 启动的调试么？如果是，还是不行，那你可以研究下 c++ 那个插件的调试是否可用，xmake-vscode 插件也是直接直接调用  c++ 的插件里面的调试功能。

或者切换到 codelldb 插件调试，相关使用 issues 有很多说明，你可以找下

**Comment by huangqi329** [comment]
切换到codelldb可以了~~
