### ISSUE TITLE
关于Qt 模板

### ISSUE THREAD

**Issue by qiu-hao** [xmake-io/xmake-vscode#6]
Xmake 能增加 一些Qt模板吗？
比如
xmake create  add  -t qt_DialogWithButtonsBottom  AboutUsDialog 
创建添加一个Dialog在当前项目下
模板包括
Dialog with Buttons Bottom
Dialog wiht Buttons Right
Dialog without Buttons
Main Window
Widget

模板文件可以参考 Qt Creator 默认生成的文件

**Comment by waruqi** [comment]
这个属于xmake-vscode等编辑器插件的特性，我先迁移到这了，后面在这里跟进吧，等xmake上一些特性搞完，这边我也会做下改进来支持这些新特性。

**Comment by waruqi** [comment]
关于这块，我想了下，打算先重构下xmake create，除了支持对project template的创建，还会加上对局部组件和模块的文件的创建，然后会在xmake-vscode加上 onCreateProject/onCreateFiles两命令来适配支持它们。。

**Comment by qiu-hao** [comment]
支持你，我在用.net core asp 时，看到.net core的命令行就可以添加页面，十分的优雅，你可以参考一下

**Comment by waruqi** [comment]
我改进了下，加上了CreateProject和NewFiles两命令，你可以试试。。

![create_and_newfiles](https://user-images.githubusercontent.com/151335/65332821-fecd9d00-dbf1-11e9-8405-596fb58ed275.gif)

**Comment by qiu-hao** [comment]
我试了一下，win10上面板显示乱了，我给你发了邮件

**Comment by waruqi** [comment]
> 我试了一下，win10上面板显示乱了，我给你发了邮件

直接issues贴图，我gmail最近一段时间上不去。

**Comment by qiu-hao** [comment]
我的win10系统上，vscode xmake命令显示这样

![Code_2019-09-20_22-19-16](https://user-images.githubusercontent.com/50729682/65337582-05acdd80-dbfb-11e9-82cf-773966102704.png)

只有最后一个 Qt\Widget 命令能用，

另外，添加的文件，用户可以命名类名吗，我看默认添加的类名是widgettest

其他，可以用命令行添加吗   比如：xmake --newfiles -t Qt\Widget  CustomerWidget

**Comment by waruqi** [comment]
我改了下，你更新下试试

> 另外，添加的文件，用户可以命名类名吗，我看默认添加的类名是widgettest

目前不能，就先凑合着用吧。

> 其他，可以用命令行添加吗 比如：xmake --newfiles -t Qt\Widget CustomerWidget

不能，这些还是偏向IDE的功能，暂时还不考虑加到xmake命令里面去，模板文件内置太多了，也影响xmake安装包大小，更加臃肿

**Comment by qiu-hao** [comment]
嗯，我试了一下，可以，后续有什么问题，我再持续向你反馈
