### ISSUE TITLE
xmake-vscode not available for vscodium?

### ISSUE THREAD

**Issue by devnewton** [xmake-io/xmake-vscode#64]
xmake-vscode cannot be found in vscodium extensions search.

**Comment by waruqi** [comment]
I am trying to upload extensions to open-vsx.org, but I still need to wait for this issue (https://github.com/EclipseFdn/open-vsx.org/issues/397) to be processed before I can continue uploading it

Refs

* https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by waruqi** [comment]
I have published it in openvsx. 

https://open-vsx.org/extension/tboox/xmake-vscode

**Comment by devnewton** [comment]
Thank you !

I installed the extension, but commands do nothing. For example, _XMake: run_ does not run the program, no log, no output. Maybe that's another issue.
