### ISSUE TITLE
同时安装了mingw64与ming32，无法完成切换的问题

### ISSUE THREAD

**Issue by GitYun** [xmake-io/xmake-vscode#68]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将会直接标记为Invalid。

### 描述问题

同时安装了mingw64与mingw32，从x86_64切换到i386时，无法切换到ming32版本，
一直检测的是ming64

### 期待的结果
能否在这样情况下，自动完成检测切换到mingw32呢？

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：v2.5.3
- xmake运行平台：Win10
- xmake目标平台：x86_64与i386

**Comment by waruqi** [comment]
xmake f --mingw=/mingw32 -a i386 自己切下
