### ISSUE TITLE
 “xmake.debuggingTargetsArguments” 不能正确发挥作用

### ISSUE THREAD

**Issue by lright1994** [xmake-io/xmake-vscode#69]
### 描述问题

 “xmake.debuggingTargetsArguments” 不能正确发挥作用

### 期待的结果
"xmake.debuggingTargetsArguments": {
        "tinydb" : ["tiny.db"],
        "default": []
    },
    "xmake.runningTargetsArguments": {
        "tinydb" : ["tiny.db"],
        "default": []
    }
设置完后点击运行run和debug按键，tinydb程序均可以带tinydb的参数（即"tiny.db"）运行

### 错误信息
按照targetName设置对应参数之后点击debug按键，仍然按照 **default**传参数运行
同时，run按键可以按照**tinydb**的参数运行。
很奇怪为什么run可以正确传参，而debug不行

### 相关环境

- xmake版本：1.4.4
- xmake运行平台：windows下的wsl
- xmake目标平台：linux x86_64

**Comment by waruqi** [comment]
我这里可以，target name 有没有切到 tinydb，而不是 default

![image](https://user-images.githubusercontent.com/151335/118472687-af7b9f00-b73b-11eb-9e3f-e2a4a650b090.png)
