### ISSUE TITLE
请考虑在“项目根目录”生成 compile_commands.json，而不是 .vscode

### ISSUE THREAD

**Issue by cjun714** [xmake-io/xmake-vscode#73]
**Issue:**

目前的实现，会在 `.vscode` 目录生成 `compile_commands.json`，这带来两个问题：
1. .compile_commands.json 应该整个项目就维持一份，因为这是 IDE 无关的文件，但 `.vscode` 却是个 IDE 相关的目录，我同时还用 vim，为了复用这个文件，那么还得在 vim 配置里去指向 .vscode。

2. 我使用 vscode-clangd 插件做补全，它默认在项目根目录找  `compile_commands.json`。
    为了复用，我就得指定clangd的搜索路径为 `.vscode` ( 通过设置 clangd 的 --compile-commands-dir 参数)，那么又会导致 clangd 产生的索引文件夹 `.cache`  位置也变成 `.vscode/.cache`。

不管是 `compile_commands.json` 还是 `.cache` 都应该整个项目就维持一份，尤其 `.cache` 体积还不小。
这两个文件应该尽量在项目根目录生成，而不是项目内某个 IDE 相关的目录。

**建议：**

默认就在项目根目录生成 `compile_commands.json`，这样clangd的 `.cache` 也会自动在项目根目录生成。

这样不管 vim 还是 vscode，可以直接复用不用配置，避免`.cache`重复生成和不一致。

希望予以考虑，非常感谢！

**Comment by waruqi** [comment]
默认路径是改不了了 这会破坏现有用户的配置环境 但可以给你提供一个配置项，让你自己调整生成的路径位置

**Comment by waruqi** [comment]
我加了个 xmake.compileCommandsDirectory 配置项，可以设置 `.` 切到当前根目录

**Comment by cjun714** [comment]
这也是个好方案，我原本也是考虑建议加个 path 参数，通过指定 `compile_commands.json` 路径，避免在 .vscode 下面生成。
但这有点反直觉，毕竟默认根目录生成。只有你指定其他目录，才去指定目录生成，更符合直觉，新手也更容易理解，也无需配置默认就对 vim ccls 更友好。

不过这个方案也足够好了，也足以解决所有问题。
非常感谢！
