### ISSUE TITLE
调试的时候怎么添加命令行参数

### ISSUE THREAD

**Issue by ipyffor** [xmake-io/xmake-vscode#80]
> Note: If it is a 'bug report' or 'feature request', please select the corresponding issue template, otherwise this issue will be not replied. 

### Describe the problem details
Please describe your problem details here.

**Comment by ipyffor** [comment]
使用vscode调试的时候能否先调用编译任务， 调试的时候怎么添加命令行参数

**Comment by waruqi** [comment]
见 https://github.com/xmake-io/xmake-vscode/issues/2#issuecomment-413574267
