### ISSUE TITLE
windows下vscode插件调试下断点无法进入

### ISSUE THREAD

**Issue by obqrn** [xmake-io/xmake-vscode#82]
windows下vscode插件调试：
1、下断点有问题。
![QQ图片20220105113811](https://user-images.githubusercontent.com/47202395/148156983-583e0363-f804-4997-b3bb-68c8a305dd7a.png)
就状态栏点击debug+build+调试，调试断点进不去，
![image](https://user-images.githubusercontent.com/47202395/148157360-828b5962-ad58-4547-ab8c-c64940a4401b.png)
断点提示No symbols have been loaded for this document.
2、单步调试点击没有响应，就像进不去调试一样；
3、调试会弹出控制台而不是嵌入vscode输出（右下角弹窗口：密钥“externalConsole”已弃用。请改用“console”。），run可以

**Comment by waruqi** [comment]
> 断点提示No symbols have been loaded for this document.
> 2、单步调试点击没有响应，就像进不去调试一样；

提示不是很明显么，no symbols ...

确保 debug 编译，并且设置了 add_rules("mode.debug") 确保 pdb 生成

> 3、调试会弹出控制台而不是嵌入vscode输出（右下角弹窗口：密钥“externalConsole”已弃用。请改用“console”。），run可以

跟着没关系，暂时还没完全废弃，可以用。我这 ok

![Snip20220105_1](https://user-images.githubusercontent.com/151335/148157828-635c84d9-345d-4538-a341-d6f1224af087.png)

**Comment by obqrn** [comment]
恩好谢了哈，断点问题解决了，需要在xmake.lua中添加add_rules("mode.debug")，同时需要rebuild才能重新生成相关pdb调试文件。
