### ISSUE TITLE
参数传递

### ISSUE THREAD

**Issue by wangzhankun** [xmake-io/xmake-vscode#89]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情
在调试程序时有时需要向程序内部通过`argv`传入参数，请问该怎么传递参数呢？

**Comment by waruqi** [comment]
看下 https://github.com/xmake-io/xmake-vscode/issues/2#issuecomment-413574267

**Comment by wangzhankun** [comment]
好的，谢谢。
