### ISSUE TITLE
XMake Commands infinitely hang when run in VSCode

### ISSUE THREAD

**Issue by LouChiSoft** [xmake-io/xmake-vscode#90]
### Xmake Version

v2.6.4+HEAD.9361ffcc1

### Operating System Version and Architecture

Windows 10 Pro 21H2

### Describe Bug

Running any command for the XMake VSCode extension will hang infinitely and the process will not be completed.

### Expected Behavior

XMake command should complete almost instantly as shown in videos on the extension page

### Additional Information and Error Logs

I recently learnt about XMake and wanted to test it out. I installed XMake via Winget on two Windows 10 Pro machines. I installed the VSCode extension from within VSCode and then I tried to use `XMake: CreateProject` option. On both machines an xmake terminal was opened but would infinitely hand and not create the new project.

**Comment by waruqi** [comment]
I will look at it. Can you try using `xmake create test` command to create project, then use vscode to open it first?

**Comment by LouChiSoft** [comment]
`xmake create test` works as does `xmake build` and `xmake run` if I use the integrated terminal. Trying to run `XMake: Build` from VSCode after making the project in the command line doesn't.

**Comment by waruqi** [comment]
> `xmake create test` works as does `xmake build` and `xmake run` if I use the integrated terminal. Trying to run `XMake: Build` from VSCode after making the project in the command line doesn't.

? I do not understand. Can you take a screen shot or screenshot for me?

**Comment by LouChiSoft** [comment]
Using XMake in a terminal works fine
![image](https://user-images.githubusercontent.com/55987090/157319783-4280bd05-448a-44d4-ab38-05d9eb356072.png)

But the VSCode extension does not work
![image](https://user-images.githubusercontent.com/55987090/157320133-519db7c3-7b9d-42ea-a796-dabd5b780eb8.png)
It gets stuck on this screen and no new files are being made after selecting `XMake: CreateProject` from the VSCode prompt.

**Comment by waruqi** [comment]
I can't reproduce your problem, but I just fixed a bug that failed to create a project using `xmake create`, I don't know if it will help your problem, you can try to update the xmake-vscode plugin first, and then try.

**Comment by LouChiSoft** [comment]
I have tried reinstalling the vscode extension and xmake and neither have seem to resolved the issue.
