### ISSUE TITLE
 vscode1.6.0版本xmake插件失效

### ISSUE THREAD

**Issue by wangzhankun** [xmake-io/xmake-vscode#94]
### Xmake 版本

2.6.3

### 操作系统版本和架构

Windows11 WSL2

### 描述问题

vscode在升级至最新的1.66.0版本后，xmake插件失效。未显示任何消息，但是xmake插件的按钮不再显示。

### 期待的结果

xmake-vscode兼容1.66.0版本

**Comment by waruqi** [comment]
> vscode在升级至最新的1.66.0版本后，xmake插件失效。未显示任何消息，但是xmake插件的按钮不再显示。

插件重装下呢？我这 1.66 用最新的 1.5.3 版本是可以的

**Comment by wangzhankun** [comment]
> > vscode在升级至最新的1.66.0版本后，xmake插件失效。未显示任何消息，但是xmake插件的按钮不再显示。
> 
> 插件重装下呢？我这 1.66 用最新的 1.5.3 版本是可以的

重装也不行。

**Comment by waruqi** [comment]
那就不知道了 你可以拉下插件源码 加载调下

**Comment by waruqi** [comment]
我换 win 上试了下, 1.66 也可以，没啥问题，暂时无法复现，你只能自己调下了

**Comment by waruqi** [comment]
可以看下 xmake.lua 是否有语法错误，确保 xmake.lua 完全有效

**Comment by waruqi** [comment]
更新到 1.5.5 再试试呢

**Comment by wangzhankun** [comment]
> 可以看下 xmake.lua 是否有语法错误，确保 xmake.lua 完全有效

感觉跟xmake.lua关系不大，我就是升级到vscode1.66.0之后突然插件失效了。包括Windows11平台下（非wsl）也失效了。我win下的xmake是2.6.4版本。wsl下也升级到了2.6.4版本。
```lua

if(is_plat("linux")) then
    set_languages("cxx11")
    add_links("pthread")
else
    -- windows
    add_defines("NOMINMAX")
end


includes("src")

target("CodeCraft-2021")
    set_kind("binary")
    set_rules("mode.debug", "mode.release")
    -- add_files("src/*.cpp")
    -- set_optimize("fastest")
    if(is_mode("debug")) then
        add_defines("TEST")
    else
        set_optimize("fastest")
    end

```

**Comment by wangzhankun** [comment]
> 更新到 1.5.5 再试试呢

插件更新到1.5.5问题解决了，谢谢。

**Comment by waruqi** [comment]
> > 更新到 1.5.5 再试试呢
> 
> 插件更新到1.5.5问题解决了，谢谢。

就是 xmake.lua 的问题，我 1.5.5 修复的，就是 xmake.lua 有语法错误，导致加载报错后失效。。

**Comment by wangzhankun** [comment]
可是我自己在命令行编译是成功的哎。
