### ISSUE TITLE
Cannot read properties of undefined(reading 'forEach')

### ISSUE THREAD

**Issue by wangzhankun** [xmake-io/xmake-vscode#95]
### Xmake 版本

2.6.4

### 操作系统版本和架构

Windows11 和 wsl2都报错

### 描述问题

插件升级到1.5.5之后，点击build按钮，右下角提示`Cannot read properties of undefined(reading 'forEach')`

### 期待的结果

能够按照需求正确执行。

### 工程配置

```lua
if(is_plat("linux")) then
    set_languages("cxx11")
    add_links("pthread")
else
    -- windows
    add_defines("NOMINMAX")
end


includes("src")

target("CodeCraft-2021")
    set_kind("binary")
    set_rules("mode.debug", "mode.release")
    -- add_files("src/*.cpp")
    -- set_optimize("fastest")
    if(is_mode("debug")) then
        add_defines("TEST")
    else
        set_optimize("fastest")
    end
```

**Comment by q962** [comment]
https://github.com/xmake-io/xmake-vscode/blob/1145987808f7cf33dafeb183b26ed5010f4eecbb/src/explorer.ts#L816

xmake 可执行文件没有通过 config 获取

**Comment by waruqi** [comment]
> https://github.com/xmake-io/xmake-vscode/blob/1145987808f7cf33dafeb183b26ed5010f4eecbb/src/explorer.ts#L816
> 
> xmake 可执行文件没有通过 config 获取

？ 来个 pr 修下？

**Comment by waruqi** [comment]
更新到 1.5.6 再试试

**Comment by q962** [comment]
有事耽搁了， 将 xmake 移除 PATH，打开控制台会得到

```shell
[Extension Host] os.execv: xmake l c:\Users\username\.vscode\extensions\tboox.xmake-vscode-1.5.6\assets\explorer.lua
ERR [Extension Host] spawn xmake ENOENT
```
>  当添加了path 就会变成 
> `os.execv: D:/xmake/xmake.exe l c:\Users\username\.vscode\extensions\tboox.xmake-vscode-1.5.6\assets\config.lua`
> 无错误

这个错误就是因为 找不到 xmake，所以 readInfo 返回 null 

https://github.com/xmake-io/xmake-vscode/blob/f905ab9bbc3da2fb9b2afa90618809c291039ccb/src/explorer.ts#L670-L673

最终导致没有执行 extractOptionValues 函数

更新后的问题是

https://github.com/xmake-io/xmake-vscode/blob/f905ab9bbc3da2fb9b2afa90618809c291039ccb/src/explorer.ts#L564-L565
https://github.com/xmake-io/xmake-vscode/blob/f905ab9bbc3da2fb9b2afa90618809c291039ccb/src/explorer.ts#L603-L605

_optionDefinitions 是否有必要设置一个默认值？

**Comment by wangzhankun** [comment]
请问这个也可以解决wsl的错误吗？

**Comment by wangzhankun** [comment]
好的。1.5.6解决了。WSL2和Windows11都测试成功。
